# Brazilian Portuguese translation for nova
# Copyright (c) 2011 Rosetta Contributors and Canonical Ltd 2011
# This file is distributed under the same license as the nova package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2011.
#
msgid ""
msgstr ""
"Project-Id-Version: nova\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2011-02-21 10:03-0500\n"
"PO-Revision-Date: 2012-01-18 19:48+0000\n"
"Last-Translator: Rafael Neri <Unknown>\n"
"Language-Team: Brazilian Portuguese <pt_BR@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2012-01-19 05:06+0000\n"
"X-Generator: Launchpad (build 14692)\n"

#: ../nova/scheduler/chance.py:37 ../nova/scheduler/zone.py:55
#: ../nova/scheduler/simple.py:75 ../nova/scheduler/simple.py:110
#: ../nova/scheduler/simple.py:122
msgid "No hosts found"
msgstr "Hosts não encontrados"

#: ../nova/exception.py:69
msgid "Unexpected error while running command."
msgstr "Erro inesperado ao executar o comando."

#: ../nova/exception.py:72
#, python-format
msgid ""
"%(description)s\n"
"Command: %(cmd)s\n"
"Exit code: %(exit_code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"
msgstr ""
"%(description)s\n"
"Comando: %(cmd)s\n"
"Código de saída: %(exit_code)s\n"
"Saída padrão: %(stdout)r\n"
"Erro: %(stderr)r"

#: ../nova/exception.py:107
msgid "DB exception wrapped"
msgstr ""

#. exc_type, exc_value, exc_traceback = sys.exc_info()
#: ../nova/exception.py:127
msgid "Uncaught exception"
msgstr "Exceção não capturada"

#: ../nova/volume/api.py:45
#, python-format
msgid "Quota exceeeded for %(pid)s, tried to create %(size)sG volume"
msgstr "Cota excedida para %(pid)s, tentando criar volume com %(size)sG"

#: ../nova/volume/api.py:57
#, python-format
msgid "Volume quota exceeded. You cannot create a volume of size %sG"
msgstr ""
"Cota excedida para o volume. Você não pode criar um volume com o tamanho %sG"

#: ../nova/volume/api.py:102 ../nova/volume/api.py:172
#: ../nova/volume/api.py:230
msgid "Volume status must be available"
msgstr "O status do volume parece estar disponível"

#: ../nova/volume/api.py:174
msgid "Volume is already attached"
msgstr "O Volume já está anexado"

#: ../nova/volume/api.py:180
msgid "Volume is already detached"
msgstr "O Volume já está desanexado"

#: ../nova/api/openstack/servers.py:72
msgid "Failed to read private ip"
msgstr "Falha ao ler o IP privado"

#: ../nova/api/openstack/servers.py:79
msgid "Failed to read public ip(s)"
msgstr "Falha ao ler o(s) IP(s) público(s)"

#: ../nova/api/openstack/servers.py:152
#, python-format
msgid "%(param)s property not found for image %(_image_id)s"
msgstr "%(param)s propriedade não foi encontrada para %(_image_id)s"

#: ../nova/api/openstack/servers.py:168
msgid "No keypairs defined"
msgstr "Os keypairs não foram definidos"

#: ../nova/api/openstack/v2/contrib/admin_actions.py:177
#, python-format
msgid "Compute.api::lock %s"
msgstr "Compute.api::lock %s"

#: ../nova/api/openstack/v2/contrib/admin_actions.py:193
#, python-format
msgid "Compute.api::unlock %s"
msgstr "Compute.api::unlock %s"

#: ../nova/api/openstack/servers.py:388
#, python-format
msgid "Compute.api::get_lock %s"
msgstr "Compute.api::get_lock %s"

#: ../nova/api/openstack/v2/contrib/admin_actions.py:145
#, python-format
msgid "Compute.api::reset_network %s"
msgstr "Compute.api::reset_network %s"

#: ../nova/api/openstack/v2/contrib/admin_actions.py:64
#, python-format
msgid "Compute.api::pause %s"
msgstr "Compute.api::pause %s"

#: ../nova/api/openstack/v2/contrib/admin_actions.py:81
#, python-format
msgid "Compute.api::unpause %s"
msgstr "Compute.api::unpause %s"

#: ../nova/api/openstack/v2/contrib/admin_actions.py:98
#, python-format
msgid "compute.api::suspend %s"
msgstr "compute.api::suspend %s"

#: ../nova/api/openstack/v2/contrib/admin_actions.py:115
#, python-format
msgid "compute.api::resume %s"
msgstr "compute.api::resume %s"

#: ../nova/virt/xenapi/volumeops.py:48 ../nova/virt/xenapi/volumeops.py:101
#: ../nova/db/sqlalchemy/api.py:731 ../nova/virt/libvirt_conn.py:741
#: ../nova/api/ec2/__init__.py:317
#, python-format
msgid "Instance %s not found"
msgstr "Instancia %s não encontrada"

#. NOTE: No Resource Pool concept so far
#: ../nova/virt/xenapi/volumeops.py:50
#, python-format
msgid "Attach_volume: %(instance_name)s, %(device_path)s, %(mountpoint)s"
msgstr "Attach_volume: %(instance_name)s, %(device_path)s, %(mountpoint)s"

#: ../nova/virt/xenapi/volumeops.py:174
#, python-format
msgid "Unable to create VDI on SR %(sr_ref)s for instance %(instance_name)s"
msgstr ""
"Não é possível criar o VDI no SR %(sr_ref)s para a instância "
"%(instance_name)s"

#: ../nova/virt/xenapi/volumeops.py:187
#, python-format
msgid "Unable to use SR %(sr_ref)s for instance %(instance_name)s"
msgstr ""
"Não é possível usar o SR %(sr_ref)s para a instância %(instance_name)s"

#: ../nova/virt/xenapi/volumeops.py:195
#, python-format
msgid "Unable to attach volume to instance %s"
msgstr "Não é possível anexar o volume na instância %s"

#: ../nova/virt/xenapi/volumeops.py:198
#, python-format
msgid "Mountpoint %(mountpoint)s attached to instance %(instance_name)s"
msgstr ""
"Ponto de montagem %(mountpoint)s conectada à instância %(instance_name)s"

#. Detach VBD from VM
#: ../nova/virt/xenapi/volumeops.py:208
#, python-format
msgid "Detach_volume: %(instance_name)s, %(mountpoint)s"
msgstr "Detach_volume: %(instance_name)s, %(mountpoint)s"

#: ../nova/virt/xenapi/volumeops.py:216
#, python-format
msgid "Unable to locate volume %s"
msgstr "Não é possível localizar o volume %s"

#: ../nova/virt/xenapi/volumeops.py:224
#, python-format
msgid "Unable to detach volume %s"
msgstr "Não é possível desconectar o volume %s"

#: ../nova/virt/xenapi/volumeops.py:238
#, python-format
msgid "Mountpoint %(mountpoint)s detached from instance %(instance_name)s"
msgstr ""
"Ponto de montagem %(mountpoint)s desanexada da instância %(instance_name)s"

#: ../nova/compute/instance_types.py:115 ../nova/compute/instance_types.py:127
#: ../nova/compute/instance_types.py:141 ../nova/compute/instance_types.py:152
#, python-format
msgid "Unknown instance type: %s"
msgstr "Tipo de instância desconhecido: %s"

#: ../nova/crypto.py:50
msgid "Filename of root CA"
msgstr "Nome do arquivo da CA raiz"

#: ../nova/crypto.py:53
msgid "Filename of private key"
msgstr "Nome do arquivo da chave privada"

#: ../nova/crypto.py:55
msgid "Filename of root Certificate Revokation List"
msgstr "Nome de arquivo da Lista de Revogação de Certificados"

#: ../nova/crypto.py:57
msgid "Where we keep our keys"
msgstr "Aonde armazenamos nossas chaves"

#: ../nova/crypto.py:59
msgid "Where we keep our root CA"
msgstr "Onde mantemos nosso CA raiz"

#: ../nova/crypto.py:61
msgid "Should we use a CA for each project?"
msgstr "Devemos usar um CA para cada projeto?"

#: ../nova/crypto.py:65
#, python-format
msgid "Subject for certificate for users, %s for project, user, timestamp"
msgstr ""
"Assunto do certificado para usuários, %s para projeto, usuário, timestamp"

#: ../nova/crypto.py:70
#, python-format
msgid "Subject for certificate for projects, %s for project, timestamp"
msgstr "Assunto do certificado para projetos, %s para projeto, timestamp"

#: ../nova/crypto.py:75
#, python-format
msgid "Subject for certificate for vpns, %s for project, timestamp"
msgstr "Assunto do certificado para vpns, %s para projeto, timestamp"

#: ../nova/crypto.py:277
#, python-format
msgid "Flags path: %s"
msgstr "Localização dos sinalizadores: %s"

#: ../nova/scheduler/manager.py:69
#, python-format
msgid "Casting to %(topic)s %(host)s for %(method)s"
msgstr "Moldagem para %(topic)s %(host)s para %(method)s"

#: ../nova/compute/manager.py:111
#, python-format
msgid "check_instance_lock: decorating: |%s|"
msgstr "check_instance_lock: decorating: |%s|"

#: ../nova/compute/manager.py:104
#, python-format
msgid ""
"check_instance_lock: arguments: |%(self)s| |%(context)s| |%(instance_id)s|"
msgstr ""
"check_instance_lock: argumentos: |%(self)s| |%(context)s| |%(instance_id)s|"

#: ../nova/compute/manager.py:117
#, python-format
msgid "check_instance_lock: locked: |%s|"
msgstr "check_instance_lock: locked: |%s|"

#: ../nova/compute/manager.py:119
#, python-format
msgid "check_instance_lock: admin: |%s|"
msgstr "check_instance_lock: admin: |%s|"

#: ../nova/compute/manager.py:124
#, python-format
msgid "check_instance_lock: executing: |%s|"
msgstr "check_instance_lock: executando: |%s|"

#: ../nova/compute/manager.py:128
#, python-format
msgid "check_instance_lock: not executing |%s|"
msgstr "check_instance_lock: not executando |%s|"

#: ../nova/compute/manager.py:395
msgid "Instance has already been created"
msgstr "A instância já foi criada"

#: ../nova/compute/manager.py:452
#, python-format
msgid "instance %s: starting..."
msgstr "instância %s: iniciando..."

#: ../nova/virt/xenapi/vmops.py:233
#, python-format
msgid "instance %s: Failed to spawn"
msgstr "instância %s: falha na geração"

#: ../nova/compute/manager.py:233 ../nova/tests/test_cloud.py:286
#, python-format
msgid "Terminating instance %s"
msgstr "Terminando a instância %s"

#: ../nova/compute/manager.py:255
#, python-format
msgid "Deallocating address %s"
msgstr "Desalocando o endereço %s"

#: ../nova/compute/manager.py:589
#, python-format
msgid "trying to destroy already destroyed instance: %s"
msgstr "tentando destruir instância já destruida: %s"

#: ../nova/compute/manager.py:753
#, python-format
msgid "Rebooting instance %s"
msgstr "Reiniciando a instância %s"

#: ../nova/compute/manager.py:599
#, python-format
msgid ""
"trying to reboot a non-running instance: %(instance_id)s (state: %(state)s "
"expected: %(running)s)"
msgstr ""
"tentando reiniciar uma instancia com estado diferente de running: "
"%(instance_id)s (estado: %(state)s esperado: %(running)s)"

#: ../nova/compute/manager.py:813
#, python-format
msgid "instance %s: snapshotting"
msgstr "instância %s: fazendo um snapshot"

#: ../nova/compute/manager.py:651
#, python-format
msgid ""
"trying to snapshot a non-running instance: %(instance_id)s (state: %(state)s "
"expected: %(running)s)"
msgstr ""
"tentando fazer um snapshot de uma instância com estado diferente de running: "
" %(instance_id)s (estado: %(state)s esperado: %(running)s)"

#: ../nova/compute/manager.py:332
#, python-format
msgid ""
"trying to reset the password on a non-running instance: %(instance_id)s "
"(state: %(instance_state)s expected: %(expected_state)s)"
msgstr ""
"tentando limpar a senha de uma instância com estado diferente de running: "
"%(instance_id)s (estado: %(instance_state)s esperado: %(expected_state)s)"

#: ../nova/compute/manager.py:335
#, python-format
msgid "instance %s: setting admin password"
msgstr "instância %s: configurando a senha do administrador"

#: ../nova/compute/manager.py:772
#, python-format
msgid ""
"trying to inject a file into a non-running instance: %(instance_id)s (state: "
"%(instance_state)s expected: %(expected_state)s)"
msgstr ""
"tentando injetar o arquivo dentro de uma instância com estado diferente de "
"running:  %(instance_id)s (estado: %(instance_state)s esperado: "
"%(expected_state)s)"

#: ../nova/compute/manager.py:362
#, python-format
msgid "instance %(nm)s: injecting file to %(plain_path)s"
msgstr "instância %(nm)s: injetando um arquivo para %(plain_path)s"

#: ../nova/compute/manager.py:990
#, python-format
msgid "instance %s: rescuing"
msgstr "instância %s: resgatando"

#: ../nova/compute/manager.py:1013
#, python-format
msgid "instance %s: unrescuing"
msgstr "instância %s: desfazendo o resgate"

#: ../nova/compute/manager.py:1302
#, python-format
msgid "instance %s: pausing"
msgstr "instância %s: pausando"

#: ../nova/compute/manager.py:1320
#, python-format
msgid "instance %s: unpausing"
msgstr "instância %s: saindo do pause"

#: ../nova/compute/manager.py:1349
#, python-format
msgid "instance %s: retrieving diagnostics"
msgstr "instância %s: recuperando os diagnósticos"

#: ../nova/compute/manager.py:1358
#, python-format
msgid "instance %s: suspending"
msgstr "instância %s: suspendendo"

#: ../nova/compute/manager.py:1380
#, python-format
msgid "instance %s: resuming"
msgstr "instância %s: resumindo"

#: ../nova/compute/manager.py:1403
#, python-format
msgid "instance %s: locking"
msgstr "instância %s: bloqueando"

#: ../nova/compute/manager.py:1412
#, python-format
msgid "instance %s: unlocking"
msgstr "instância %s: desbloqueando"

#: ../nova/compute/manager.py:1420
#, python-format
msgid "instance %s: getting locked state"
msgstr "instância %s: obtendo estado de bloqueio"

#: ../nova/compute/manager.py:1430
#, python-format
msgid "instance %s: reset network"
msgstr "instância %s: reset da rede"

#: ../nova/compute/manager.py:1452 ../nova/api/ec2/cloud.py:823
#, python-format
msgid "Get console output for instance %s"
msgstr "Obter saída do console para instância %s"

#: ../nova/compute/manager.py:1477
#, python-format
msgid "instance %s: getting ajax console"
msgstr "instância %s: obtendo console ajax"

#: ../nova/compute/manager.py:1239
#, python-format
msgid ""
"instance %(instance_id)s: attaching volume %(volume_id)s to %(mountpoint)s"
msgstr ""
"instância %(instance_id)s: atachando volume %(volume_id)s para %(mountpoint)s"

#. pylint: disable=W0702
#. NOTE(vish): The inline callback eats the exception info so we
#. log the traceback here and reraise the same
#. ecxception below.
#: ../nova/compute/manager.py:1265
#, python-format
msgid "instance %(instance_id)s: attach failed %(mountpoint)s, removing"
msgstr ""
"instância %(instance_id)s: falha ao atachar ponto de montagem "
"%(mountpoint)s, removendo"

#: ../nova/compute/manager.py:1472
#, python-format
msgid ""
"Detach volume %(volume_id)s from mountpoint %(mp)s on instance "
"%(instance_id)s"
msgstr ""
"Desconectando volume %(volume_id)s do ponto de montagem %(mp)s na instância "
"%(instance_id)s"

#: ../nova/compute/manager.py:1559
#, python-format
msgid "Detaching volume from unknown instance %s"
msgstr "Desconectando volume da instância desconhecida %s"

#: ../nova/scheduler/simple.py:52
#, python-format
msgid "Host %s is not alive"
msgstr "Host %s não está ativo"

#: ../nova/scheduler/simple.py:67
msgid "All hosts have too many cores"
msgstr "Todos os hosts tem muitos núcleos de CPU"

#: ../nova/scheduler/simple.py:94 ../nova/scheduler/vsa.py:223
#, python-format
msgid "Host %s not available"
msgstr "O host %s não está disponível"

#: ../nova/scheduler/simple.py:119
msgid "All hosts have too many gigabytes"
msgstr "Todos os hosts tem muitos gigabytes"

#: ../nova/scheduler/simple.py:136
msgid "All hosts have too many networks"
msgstr "Todos os hosts tem muitas interfaces de rede"

#: ../nova/volume/manager.py:89
#, python-format
msgid "Re-exporting %s volumes"
msgstr "Re-exportando %s volumes"

#: ../nova/volume/manager.py:94
#, python-format
msgid "volume %s: skipping export"
msgstr "volume %s: ignorando export"

#: ../nova/volume/manager.py:100
#, python-format
msgid "volume %s: creating"
msgstr "volume %s: criando"

#: ../nova/volume/manager.py:112
#, python-format
msgid "volume %(vol_name)s: creating lv of size %(vol_size)sG"
msgstr "volume %(vol_name)s: criando lv com tamanho %(vol_size)sG"

#: ../nova/volume/manager.py:124
#, python-format
msgid "volume %s: creating export"
msgstr "volume %s: criando o export"

#: ../nova/volume/manager.py:138
#, python-format
msgid "volume %s: created successfully"
msgstr "volume %s: criado com sucesso"

#: ../nova/volume/manager.py:167
msgid "Volume is still attached"
msgstr "O volume continua atachado"

#: ../nova/volume/manager.py:169
msgid "Volume is not local to this node"
msgstr "O volume não pertence à este node"

#: ../nova/volume/manager.py:173
#, python-format
msgid "volume %s: removing export"
msgstr "volume %s: removendo export"

#: ../nova/volume/manager.py:175
#, python-format
msgid "volume %s: deleting"
msgstr "volume %s: removendo"

#: ../nova/volume/manager.py:190
#, python-format
msgid "volume %s: deleted successfully"
msgstr "volume %s: remoção realizada com sucesso"

#: ../nova/virt/xenapi/fake.py:77 ../nova/virt/vmwareapi/fake.py:44
#, python-format
msgid "%(text)s: _db_content => %(content)s"
msgstr "%(text)s: _db_content => %(content)s"

#: ../nova/virt/xenapi/fake.py:495 ../nova/virt/xenapi/fake.py:594
#: ../nova/virt/xenapi/fake.py:612 ../nova/virt/xenapi/fake.py:675
msgid "Raising NotImplemented"
msgstr "Aumento não implementado"

#: ../nova/virt/xenapi/fake.py:497
#, python-format
msgid "xenapi.fake does not have an implementation for %s"
msgstr "xenapi.fake não tem uma implementação para %s"

#: ../nova/virt/xenapi/fake.py:531
#, python-format
msgid "Calling %(localname)s %(impl)s"
msgstr "Chamando %(localname)s %(impl)s"

#: ../nova/virt/xenapi/fake.py:536
#, python-format
msgid "Calling getter %s"
msgstr "Chamando o pai %s"

#: ../nova/virt/xenapi/fake.py:596
#, python-format
msgid ""
"xenapi.fake does not have an implementation for %s or it has been called "
"with the wrong number of arguments"
msgstr ""
"xenapi.fake não tem implementação para %s ou isto foi chamado com um número "
"de argumentos inválidos"

#: ../nova/tests/test_cloud.py:256
msgid "Can't test instances without a real virtual env."
msgstr "Não é possível testar instâncias sem um ambiente virtual real"

#: ../nova/tests/test_cloud.py:268
#, python-format
msgid "Need to watch instance %s until it's running..."
msgstr "É necessário assistir a instância %s até ela estar rodando..."

#: ../nova/virt/connection.py:78
msgid "Failed to open connection to the hypervisor"
msgstr "Falha ao abrir a conexão com o hypervisor"

#: ../nova/network/linux_net.py:937
#, python-format
msgid "Starting VLAN inteface %s"
msgstr "Iniciando a VLAN %s"

#: ../nova/network/linux_net.py:969
#, python-format
msgid "Starting Bridge interface for %s"
msgstr "Iniciando a Bridge para %s"

#. pylint: disable=W0703
#: ../nova/network/linux_net.py:669
#, python-format
msgid "Hupping dnsmasq threw %s"
msgstr ""

#: ../nova/network/linux_net.py:671
#, python-format
msgid "Pid %d is stale, relaunching dnsmasq"
msgstr "Pid %d está ultrapassado, reiniciando dnsmasq"

#. pylint: disable=W0703
#: ../nova/network/linux_net.py:731
#, python-format
msgid "killing radvd threw %s"
msgstr ""

#: ../nova/network/linux_net.py:733
#, python-format
msgid "Pid %d is stale, relaunching radvd"
msgstr "Pid %d está ultrapassado, reiniciando radvd"

#. pylint: disable=W0703
#: ../nova/network/linux_net.py:763
#, python-format
msgid "Killing dnsmasq threw %s"
msgstr ""

#: ../nova/utils.py:66
#, python-format
msgid "Inner Exception: %s"
msgstr "Exceção interna: %s"

#: ../nova/utils.py:59
#, python-format
msgid "Class %s cannot be found"
msgstr "Classe %s não pode ser encontrada"

#: ../nova/utils.py:150
#, python-format
msgid "Fetching %s"
msgstr "Obtendo %s"

#: ../nova/utils.py:201
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr "Executando comando (subprocesso): %s"

#: ../nova/utils.py:217 ../nova/utils.py:297
#, python-format
msgid "Result was %s"
msgstr "Resultado foi %s"

#: ../nova/utils.py:273
#, python-format
msgid "Running cmd (SSH): %s"
msgstr "Rodando o comando (SSH): %s"

#: ../nova/utils.py:337
#, python-format
msgid "debug in callback: %s"
msgstr "debug em callback: %s"

#: ../nova/utils.py:342
#, python-format
msgid "Running %s"
msgstr "Executando %s"

#: ../nova/utils.py:470
#, python-format
msgid "Link Local address is not found.:%s"
msgstr "Endereço para Link Local não encontrado: %s"

#: ../nova/utils.py:473
#, python-format
msgid "Couldn't get Link Local IP of %(interface)s :%(ex)s"
msgstr ""
"Não foi possível atribuir um IP para o Link Local de %(interface)s :%(ex)s"

#: ../nova/utils.py:570
#, python-format
msgid "Invalid backend: %s"
msgstr "Backend inválido: %s"

#: ../nova/utils.py:581
#, python-format
msgid "backend %s"
msgstr "backend %s"

#: ../nova/testing/fake/rabbit.py:50
#, python-format
msgid "(%(nm)s) publish (key: %(routing_key)s) %(message)s"
msgstr "(%(nm)s) publicar (key: %(routing_key)s) %(message)s"

#: ../nova/testing/fake/rabbit.py:54
#, python-format
msgid "Publishing to route %s"
msgstr "Publicando para rota %s"

#: ../nova/testing/fake/rabbit.py:84
#, python-format
msgid "Declaring queue %s"
msgstr "Declarando fila %s"

#: ../nova/testing/fake/rabbit.py:90
#, python-format
msgid "Declaring exchange %s"
msgstr "Declarando troca %s"

#: ../nova/testing/fake/rabbit.py:96
#, python-format
msgid "Binding %(queue)s to %(exchange)s with key %(routing_key)s"
msgstr "Ligação %(queue)s para %(exchange)s com chave %(routing_key)s"

#: ../nova/testing/fake/rabbit.py:133
#, python-format
msgid "Getting from %(queue)s: %(message)s"
msgstr "Recebendo de %(queue)s: %(message)s"

#: ../nova/virt/xenapi/vm_utils.py:189 ../nova/virt/hyperv.py:189
#, python-format
msgid "Created VM %s..."
msgstr "VM %s criada..."

#: ../nova/virt/xenapi/vm_utils.py:192
#, python-format
msgid "Created VM %(instance_name)s as %(vm_ref)s."
msgstr "VM %(instance_name)s criada como %(vm_ref)s."

#: ../nova/virt/xenapi/volume_utils.py:206
#, python-format
msgid "Creating VBD for VM %(vm_ref)s, VDI %(vdi_ref)s ... "
msgstr "Criando VBD para VM %(vm_ref)s, VDI %(vdi_ref)s ... "

#: ../nova/virt/xenapi/volume_utils.py:209
#, python-format
msgid "Created VBD %(vbd_ref)s for VM %(vm_ref)s, VDI %(vdi_ref)s."
msgstr "VBD %(vbd_ref)s criado para VM %(vm_ref)s, VDI %(vdi_ref)s."

#: ../nova/virt/xenapi/vm_utils.py:243
#, python-format
msgid "VBD not found in instance %s"
msgstr "O VBD não foi encontrado na instância %s"

#: ../nova/virt/xenapi/vm_utils.py:254
#, python-format
msgid "Unable to unplug VBD %s"
msgstr "Não é possível desconectar o VBD %s"

#: ../nova/virt/xenapi/vm_utils.py:265
#, python-format
msgid "Unable to destroy VBD %s"
msgstr "Não é possível destruir o VBD %s"

#: ../nova/virt/xenapi/vmops.py:1460
#, python-format
msgid "Creating VIF for VM %(vm_ref)s, network %(network_ref)s."
msgstr "Criando a VIF para VM %(vm_ref)s, rede %(network_ref)s."

#: ../nova/virt/xenapi/vmops.py:1463
#, python-format
msgid "Created VIF %(vif_ref)s for VM %(vm_ref)s, network %(network_ref)s."
msgstr "VIF %(vif_ref)s criada para VM %(vm_ref)s, rede %(network_ref)s."

#: ../nova/virt/xenapi/vm_utils.py:292
#, python-format
msgid ""
"Created VDI %(vdi_ref)s (%(name_label)s, %(virtual_size)s, %(read_only)s) on "
"%(sr_ref)s."
msgstr ""
"VDI %(vdi_ref)s (%(name_label)s, %(virtual_size)s, %(read_only)s) no SR "
"%(sr_ref)s criada com sucesso."

#: ../nova/virt/xenapi/vm_utils.py:319
#, python-format
msgid "Snapshotting VM %(vm_ref)s with label '%(label)s'..."
msgstr "Fazendo um snapshot da VM %(vm_ref)s com rótulo '%(label)s'..."

#: ../nova/virt/xenapi/vm_utils.py:333
#, python-format
msgid "Created snapshot %(template_vm_ref)s from VM %(vm_ref)s."
msgstr "Snapshot %(template_vm_ref)s criado a partir da VM %(vm_ref)s."

#. NOTE(sirp): Currently we only support uploading images as VHD, there
#. is no RAW equivalent (yet)
#: ../nova/virt/xenapi/vm_utils.py:363
#, python-format
msgid "Asking xapi to upload %(vdi_uuids)s as ID %(image_id)s"
msgstr ""
"Solicitando à xapi para realizar upload da imagem %(vdi_uuids)s com ID "
"%(image_id)s"

#: ../nova/virt/xenapi/vm_utils.py:327
#, python-format
msgid "Size for image %(image)s:%(virtual_size)d"
msgstr "Tamanho da imagem %(image)s:%(virtual_size)d"

#. TODO(sirp): This should eventually be the URI for the Glance image
#: ../nova/virt/xenapi/vm_utils.py:1157
#, python-format
msgid "Glance image %s"
msgstr "Visão geral da imagem %s"

#. We need to invoke a plugin for copying the
#. content of the VDI into the proper path.
#: ../nova/virt/xenapi/vm_utils.py:668
#, python-format
msgid "Copying VDI %s to /boot/guest on dom0"
msgstr "Copiando o VDI %s de /boot/guest no dom0"

#: ../nova/virt/xenapi/vm_utils.py:678
#, python-format
msgid "Kernel/Ramdisk VDI %s destroyed"
msgstr "Kernel/Ramdisk %s destruidos"

#: ../nova/virt/xenapi/vm_utils.py:361
#, python-format
msgid "Asking xapi to fetch %(url)s as %(access)s"
msgstr "Requisitando à xapi a busca da url %(url)s como %(access)s"

#: ../nova/virt/xenapi/vm_utils.py:756
#, python-format
msgid "Looking up vdi %s for PV kernel"
msgstr "Verificando o vdi %s para kernel PV"

#: ../nova/virt/xenapi/vm_utils.py:397
#, python-format
msgid "PV Kernel in VDI:%s"
msgstr "Kernel PV no VDI: %s"

#: ../nova/virt/xenapi/vm_utils.py:1299
#, python-format
msgid "Running pygrub against %s"
msgstr "Rodando pygrub novamente %s"

#: ../nova/virt/xenapi/vm_utils.py:1306
#, python-format
msgid "Found Xen kernel %s"
msgstr "Kernel Xen encontrado: %s"

#: ../nova/virt/xenapi/vm_utils.py:1308
msgid "No Xen kernel found.  Booting HVM."
msgstr "Kernel Xen não encontrado. Iniciando como HVM."

#: ../nova/virt/hyperv.py:449
#, python-format
msgid "duplicate name found: %s"
msgstr "nome duplicado encontrado: %s"

#: ../nova/virt/xenapi/vm_utils.py:816
#, python-format
msgid "VDI %s is still available"
msgstr "O VDI %s continua disponível"

#: ../nova/virt/xenapi/vm_utils.py:862
#, python-format
msgid "(VM_UTILS) xenserver vm state -> |%s|"
msgstr "(VM_UTILS) xenserver vm state -> |%s|"

#: ../nova/virt/xenapi/vm_utils.py:864
#, python-format
msgid "(VM_UTILS) xenapi power_state -> |%s|"
msgstr "(VM_UTILS) xenapi power_state -> |%s|"

#: ../nova/virt/xenapi/vm_utils.py:1106
#, python-format
msgid "VHD %(vdi_uuid)s has parent %(parent_ref)s"
msgstr "O VHD %(vdi_uuid)s tem pai %(parent_ref)s"

#: ../nova/virt/xenapi/vm_utils.py:920
#, python-format
msgid "Re-scanning SR %s"
msgstr "Re-escaneando SR %s"

#: ../nova/virt/xenapi/vm_utils.py:1157
#, python-format
msgid ""
"VHD coalesce attempts exceeded (%(counter)d > %(max_attempts)d), giving up..."
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:1164
#, python-format
msgid ""
"Parent %(parent_uuid)s doesn't match original parent "
"%(original_parent_uuid)s, waiting for coalesce..."
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:911
#, python-format
msgid "No VDIs found for VM %s"
msgstr "Nenhum VDIs encontrado para MV %s"

#: ../nova/virt/xenapi/vm_utils.py:594
#, python-format
msgid "Unexpected number of VDIs (%(num_vdis)s) found for VM %(vm_ref)s"
msgstr ""
"Número de VDIs inesperado (%(num_vdis)s) encontrado para MV %(vm_ref)s"

#: ../nova/virt/xenapi/vm_utils.py:1226
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:188
#, python-format
msgid "Creating VBD for VDI %s ... "
msgstr "Criando VBD para VDI %s ... "

#: ../nova/virt/xenapi/vm_utils.py:1228
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:190
#, python-format
msgid "Creating VBD for VDI %s done."
msgstr "O VBD para VDI %s foi criado."

#: ../nova/virt/xenapi/vm_utils.py:1230
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:192
#, python-format
msgid "Plugging VBD %s ... "
msgstr "Conectando VBD %s ... "

#: ../nova/virt/xenapi/vm_utils.py:1233
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:194
#, python-format
msgid "Plugging VBD %s done."
msgstr "O VDB %s foi conectado."

#: ../nova/virt/xenapi/vm_utils.py:661
#, python-format
msgid "VBD %(vbd)s plugged as %(orig_dev)s"
msgstr "VBD %(vbd)s conectado como %(orig_dev)s"

#: ../nova/virt/xenapi/vm_utils.py:664
#, python-format
msgid "VBD %(vbd)s plugged into wrong dev, remapping to %(dev)s"
msgstr "VBD %(vbd)s conectado no device errado, remapeando para %(dev)s"

#: ../nova/virt/xenapi/vm_utils.py:1247
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:197
#, python-format
msgid "Destroying VBD for VDI %s ... "
msgstr "Destruindo VBD para o VDI %s ... "

#: ../nova/virt/xenapi/vm_utils.py:1251
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:200
#, python-format
msgid "Destroying VBD for VDI %s done."
msgstr "O VBD para o VDI %s foi destruído."

#: ../nova/virt/xenapi/vm_utils.py:1263
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:211
msgid "VBD.unplug successful first time."
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:1268
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:216
msgid "VBD.unplug rejected: retrying..."
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:1273
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:220
msgid "VBD.unplug successful eventually."
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:1276
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:223
#, python-format
msgid "Ignoring XenAPI.Failure in VBD.unplug: %s"
msgstr "Ignorando XenAPI.Failure em VBD.unplug: %s"

#: ../nova/virt/xenapi/vm_utils.py:1285
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:66
#, python-format
msgid "Ignoring XenAPI.Failure %s"
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:1140
#, python-format
msgid ""
"Writing partition table %(primary_first)d %(primary_last)d to %(dest)s..."
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:1366
#, python-format
msgid "Writing partition table %s done."
msgstr ""

#: ../nova/tests/rpc/common.py:142
#, python-format
msgid "Nested received %(queue)s, %(value)s"
msgstr ""

#: ../nova/tests/rpc/common.py:150
#, python-format
msgid "Nested return %s"
msgstr ""

#: ../nova/tests/rpc/common.py:176 ../nova/tests/rpc/common.py:182
#, python-format
msgid "Received %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:52
msgid "Use of empty request context is deprecated"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:133
#, python-format
msgid "No service for id %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:251
#, python-format
msgid "No service for %(host)s, %(binary)s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:592
msgid "No fixed ips defined"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:608
#, python-format
msgid "No floating ip for address %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:629
#, python-format
msgid "No address for instance %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:961
#, python-format
msgid "no keypair for user %(user_id)s, name %(name)s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1076 ../nova/db/sqlalchemy/api.py:1156
#, python-format
msgid "No network for id %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1086
msgid "No networks defined"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1115
#, python-format
msgid "No network for bridge %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1129 ../nova/db/sqlalchemy/api.py:1142
#, python-format
msgid "No network for instance %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1277
#, python-format
msgid "Token %s does not exist"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1302
#, python-format
msgid "No quota for project_id %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1455 ../nova/db/sqlalchemy/api.py:1501
#: ../nova/api/ec2/__init__.py:323
#, python-format
msgid "Volume %s not found"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1514
#, python-format
msgid "No export device found for volume %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1527
#, python-format
msgid "No target id found for volume %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1572
#, python-format
msgid "No security group with id %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1589
#, python-format
msgid "No security group named %(group_name)s for project: %(project_id)s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1682
#, python-format
msgid "No secuity group rule with id %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1756
#, python-format
msgid "No user for id %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1772
#, python-format
msgid "No user for access key %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1834
#, python-format
msgid "No project with id %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1979
#, python-format
msgid "No console pool with id %(pool_id)s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1996
#, python-format
msgid ""
"No console pool of type %(console_type)s for compute host %(compute_host)s "
"on proxy host %(host)s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:2035
#, python-format
msgid "No console for instance %(instance_id)s in pool %(pool_id)s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:2057
#, python-format
msgid "on instance %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:2058
#, python-format
msgid "No console with id %(console_id)s %(idesc)s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:2078 ../nova/db/sqlalchemy/api.py:2097
#, python-format
msgid "No zone with id %(zone_id)s"
msgstr ""

#: ../nova/compute/manager.py:221
#, python-format
msgid "Checking state of %s"
msgstr ""

#: ../nova/virt/libvirt_conn.py:165
#, python-format
msgid "Current state of %(name)s was %(state)s."
msgstr ""

#: ../nova/virt/libvirt/connection.py:228
#, python-format
msgid "Connecting to libvirt: %s"
msgstr ""

#: ../nova/virt/libvirt/connection.py:242
msgid "Connection to libvirt broke"
msgstr ""

#: ../nova/virt/libvirt/connection.py:403
#, python-format
msgid "instance %(instance_name)s: deleting instance files %(target)s"
msgstr ""

#: ../nova/virt/libvirt_conn.py:283
#, python-format
msgid "Invalid device path %s"
msgstr ""

#: ../nova/virt/libvirt_conn.py:313
#, python-format
msgid "No disk at %s"
msgstr ""

#: ../nova/virt/libvirt_conn.py:320
msgid "Instance snapshotting is not supported for libvirtat this time"
msgstr ""

#: ../nova/virt/libvirt_conn.py:336
#, python-format
msgid "instance %s: rebooted"
msgstr ""

#: ../nova/virt/libvirt_conn.py:339
#, python-format
msgid "_wait_for_reboot failed: %s"
msgstr ""

#: ../nova/virt/libvirt_conn.py:382
#, python-format
msgid "instance %s: rescued"
msgstr ""

#: ../nova/virt/libvirt_conn.py:385
#, python-format
msgid "_wait_for_rescue failed: %s"
msgstr ""

#: ../nova/virt/libvirt/connection.py:680
#, python-format
msgid "instance %s: is running"
msgstr ""

#: ../nova/virt/libvirt_conn.py:422
#, python-format
msgid "instance %s: booted"
msgstr ""

#: ../nova/virt/libvirt_conn.py:425 ../nova/virt/xenapi/vmops.py:186
#, python-format
msgid "instance %s: failed to boot"
msgstr ""

#: ../nova/virt/libvirt/connection.py:703
#, python-format
msgid "virsh said: %r"
msgstr ""

#: ../nova/virt/libvirt/connection.py:707
msgid "cool, it's a device"
msgstr ""

#: ../nova/virt/libvirt/connection.py:718
#, python-format
msgid "data: %(data)r, fpath: %(fpath)r"
msgstr ""

#: ../nova/virt/libvirt/connection.py:745
#, python-format
msgid "Contents of file %(fpath)s: %(contents)r"
msgstr ""

#: ../nova/virt/libvirt/utils.py:218
msgid "Unable to find an open port"
msgstr "Impossível localizar uma porta aberta"

#: ../nova/virt/libvirt/connection.py:868
#, python-format
msgid "instance %s: Creating image"
msgstr ""

#: ../nova/virt/libvirt_conn.py:646
#, python-format
msgid "instance %(inst_name)s: injecting key into image %(img_id)s"
msgstr ""

#: ../nova/virt/libvirt_conn.py:649
#, python-format
msgid "instance %(inst_name)s: injecting net into image %(img_id)s"
msgstr ""

#. This could be a windows image, or a vmdk format disk
#: ../nova/virt/libvirt/connection.py:1058
#, python-format
msgid ""
"instance %(inst_name)s: ignoring error injecting data into image %(img_id)s "
"(%(e)s)"
msgstr ""

#. TODO(termie): cache?
#: ../nova/virt/libvirt/connection.py:1204
#, python-format
msgid "instance %s: starting toXML method"
msgstr ""

#: ../nova/virt/libvirt/connection.py:1208
#, python-format
msgid "instance %s: finished toXML method"
msgstr ""

#: ../nova/virt/libvirt/connection.py:1330
msgid "diagnostics are not supported for libvirt"
msgstr ""

#: ../nova/virt/libvirt/firewall.py:486 ../nova/virt/firewall.py:125
#, python-format
msgid "Attempted to unfilter instance %s which is not filtered"
msgstr ""

#: ../nova/api/metadata/handler.py:251 ../nova/api/metadata/handler.py:258
#, python-format
msgid "Failed to get metadata for ip: %s"
msgstr "Falha ao obter metadados para o ip: %s"

#: ../nova/auth/fakeldap.py:33
msgid "Attempted to instantiate singleton"
msgstr "Tentativa de instanciar singleton"

#: ../nova/network/api.py:39
#, python-format
msgid "Quota exceeeded for %s, tried to allocate address"
msgstr ""

#: ../nova/network/manager.py:302
msgid "Address quota exceeded. You cannot allocate any more addresses"
msgstr ""

#: ../nova/tests/test_volume.py:190
#, python-format
msgid "Target %s allocated"
msgstr ""

#: ../nova/virt/images.py:70
#, python-format
msgid "Finished retreving %(url)s -- placed in %(path)s"
msgstr ""

#: ../nova/scheduler/driver.py:169
msgid "Must implement a fallback schedule"
msgstr ""

#: ../nova/console/manager.py:71 ../nova/console/vmrc_manager.py:64
msgid "Adding console"
msgstr ""

#: ../nova/console/manager.py:91
#, python-format
msgid "Tried to remove non-existant console %(console_id)s."
msgstr ""

#: ../nova/api/direct.py:218
msgid "not available"
msgstr ""

#: ../nova/api/ec2/cloud.py:62
#, python-format
msgid "The key_pair %s already exists"
msgstr ""

#. TODO(vish): Do this with M2Crypto instead
#: ../nova/api/ec2/cloud.py:237
#: ../nova/api/openstack/v2/contrib/cloudpipe.py:82
#, python-format
msgid "Generating root CA: %s"
msgstr "Gerando CA raiz: %s"

#: ../nova/api/ec2/cloud.py:395
#, python-format
msgid "Create key pair %s"
msgstr "Criar par de chaves %s"

#: ../nova/api/ec2/cloud.py:437
#, python-format
msgid "Delete key pair %s"
msgstr "Remover par de chaves %s"

#: ../nova/api/ec2/cloud.py:386
#, python-format
msgid "%s is not a valid ipProtocol"
msgstr "%s não é um ipProtocol válido"

#: ../nova/api/ec2/cloud.py:390
msgid "Invalid port range"
msgstr "Intervalo de porta inválido"

#: ../nova/api/openstack/v2/contrib/security_groups.py:490
#, python-format
msgid "Revoke security group ingress %s"
msgstr "Revogado entrada do grupo de segurança %s"

#: ../nova/api/openstack/v2/contrib/security_groups.py:352
msgid "Not enough parameters to build a valid rule."
msgstr ""

#: ../nova/api/ec2/cloud.py:696 ../nova/api/ec2/cloud.py:752
msgid "No rule for the specified parameters."
msgstr "Não existe regra para os parâmetros especificados"

#: ../nova/api/openstack/v2/contrib/security_groups.py:337
#, python-format
msgid "Authorize security group ingress %s"
msgstr "Autorizada entrada do grupo de segurança %s"

#: ../nova/api/openstack/v2/contrib/security_groups.py:359
#, python-format
msgid "This rule already exists in group %s"
msgstr "Esta regra já existe no grupo %s"

#: ../nova/api/ec2/cloud.py:788
#: ../nova/api/openstack/v2/contrib/security_groups.py:277
#, python-format
msgid "Create Security Group %s"
msgstr "Criar Grupo de Segurança %s"

#: ../nova/api/ec2/cloud.py:791
#, python-format
msgid "group %s already exists"
msgstr "group %s já existe"

#: ../nova/api/ec2/cloud.py:818
#: ../nova/api/openstack/v2/contrib/security_groups.py:234
#, python-format
msgid "Delete security group %s"
msgstr "Excluir grupo de segurança %s"

#: ../nova/api/openstack/v2/contrib/volumes.py:182
#: ../nova/api/ec2/cloud.py:915
#, python-format
msgid "Create volume of %s GB"
msgstr "Criar volume de %s GB"

#: ../nova/api/ec2/cloud.py:950
#, python-format
msgid "Attach volume %(volume_id)s to instance %(instance_id)s at %(device)s"
msgstr ""

#: ../nova/api/openstack/v2/contrib/volumes.py:347
#: ../nova/api/ec2/cloud.py:964
#, python-format
msgid "Detach volume %s"
msgstr "Desanexar volume %s"

#: ../nova/api/ec2/cloud.py:1244
msgid "Allocate address"
msgstr "Alocar endereço"

#: ../nova/api/ec2/cloud.py:1256
#, python-format
msgid "Release address %s"
msgstr "Liberar endereço %s"

#: ../nova/api/ec2/cloud.py:1261
#, python-format
msgid "Associate address %(public_ip)s to instance %(instance_id)s"
msgstr ""

#: ../nova/api/ec2/cloud.py:1271
#, python-format
msgid "Disassociate address %s"
msgstr "Desatribuir endereço %s"

#: ../nova/api/ec2/cloud.py:1319
msgid "Going to start terminating instances"
msgstr "Começando a terminar instâncias"

#: ../nova/api/ec2/cloud.py:1328
#, python-format
msgid "Reboot instance %r"
msgstr "Reiniciar instância %r"

#: ../nova/api/ec2/cloud.py:1469
#, python-format
msgid "De-registering image %s"
msgstr "Removendo o registro da imagem %s"

#: ../nova/api/ec2/cloud.py:1496
#, python-format
msgid "Registered image %(image_location)s with id %(image_id)s"
msgstr ""

#: ../nova/api/ec2/cloud.py:991 ../nova/api/ec2/cloud.py:1048
#: ../nova/api/ec2/cloud.py:1524 ../nova/api/ec2/cloud.py:1539
#, python-format
msgid "attribute not supported: %s"
msgstr "atributo não suportado: %s"

#: ../nova/api/ec2/cloud.py:890
#, python-format
msgid "invalid id: %s"
msgstr "id inválido: %s"

#: ../nova/api/ec2/cloud.py:1542
msgid "user or group not specified"
msgstr "usuário ou grupo não especificado"

#: ../nova/api/ec2/cloud.py:1544
msgid "only group \"all\" is supported"
msgstr "apenas o grupo \"all\" é suportado"

#: ../nova/api/ec2/cloud.py:1546
msgid "operation_type must be add or remove"
msgstr "operation_type deve ser add ou remove"

#: ../nova/api/ec2/cloud.py:1547
#, python-format
msgid "Updating image %s publicity"
msgstr "Atualizando publicidade da imagem %s"

#: ../bin/nova-api.py:52
#, python-format
msgid "Using paste.deploy config at: %s"
msgstr ""

#: ../bin/nova-api.py:57
#, python-format
msgid "No paste configuration for app: %s"
msgstr ""

#: ../bin/nova-api.py:59
#, python-format
msgid ""
"App Config: %(api)s\n"
"%(config)r"
msgstr ""

#: ../bin/nova-api.py:64
#, python-format
msgid "Running %s API"
msgstr ""

#: ../bin/nova-api.py:69
#, python-format
msgid "No known API applications configured in %s."
msgstr ""

#: ../bin/nova-api.py:83
#, python-format
msgid "Starting nova-api node (version %s)"
msgstr ""

#: ../bin/nova-api.py:89
#, python-format
msgid "No paste configuration found for: %s"
msgstr ""

#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:84
#, python-format
msgid "Argument %(key)s value %(value)s is too short."
msgstr ""

#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:89
#, python-format
msgid "Argument %(key)s value %(value)s contains invalid characters."
msgstr ""

#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:94
#, python-format
msgid "Argument %(key)s value %(value)s starts with a hyphen."
msgstr ""

#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:102
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:130
#, python-format
msgid "Argument %s is required."
msgstr ""

#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:117
#, python-format
msgid ""
"Argument %(key)s may not take value %(value)s. Valid values are ['true', "
"'false']."
msgstr ""

#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:163
#, python-format
msgid ""
"Created VDI %(vdi_ref)s (%(label)s, %(size)s, %(read_only)s) on %(sr_ref)s."
msgstr ""

#: ../nova/virt/xenapi/vmops.py:67
#, python-format
msgid "Attempted to create non-unique name %s"
msgstr ""

#: ../nova/virt/xenapi/vmops.py:73
#, python-format
msgid "instance %(name)s: not enough free memory"
msgstr ""

#: ../nova/virt/xenapi/vmops.py:441
#, python-format
msgid "Starting VM %s..."
msgstr ""

#: ../nova/virt/xenapi/vmops.py:444
#, python-format
msgid "Spawning VM %(instance_name)s created %(vm_ref)s."
msgstr ""

#: ../nova/virt/xenapi/vmops.py:162
#, python-format
msgid "Invalid value for onset_files: '%s'"
msgstr ""

#: ../nova/virt/xenapi/vmops.py:418
#, python-format
msgid "Injecting file path: '%s'"
msgstr ""

#: ../nova/virt/xenapi/vmops.py:467
#, python-format
msgid "Instance %s: booted"
msgstr ""

#: ../nova/virt/xenapi/vmops.py:232
#, python-format
msgid "Instance not present %s"
msgstr ""

#. TODO(sirp): Add quiesce and VSS locking support when Windows support
#. is added
#: ../nova/virt/xenapi/vmops.py:614
#, python-format
msgid "Starting snapshot for VM %s"
msgstr ""

#: ../nova/virt/xenapi/vmops.py:623
#, python-format
msgid "Unable to Snapshot %(vm_ref)s: %(exc)s"
msgstr ""

#: ../nova/virt/xenapi/vmops.py:608
#, python-format
msgid "Finished snapshot and upload for VM %s"
msgstr ""

#: ../nova/virt/xenapi/vmops.py:356
#, python-format
msgid "VM %(vm)s already halted, skipping shutdown..."
msgstr ""

#: ../nova/virt/xenapi/vmops.py:389
msgid "Removing kernel/ramdisk files"
msgstr ""

#: ../nova/virt/xenapi/vmops.py:1091
msgid "kernel/ramdisk files removed"
msgstr ""

#: ../nova/virt/xenapi/vmops.py:561
#, python-format
msgid ""
"TIMEOUT: The call to %(method)s timed out. VM id=%(instance_id)s; "
"args=%(strargs)s"
msgstr ""

#: ../nova/virt/xenapi/vmops.py:564
#, python-format
msgid ""
"NOT IMPLEMENTED: The call to %(method)s is not supported by the agent. VM "
"id=%(instance_id)s; args=%(strargs)s"
msgstr ""

#: ../nova/virt/xenapi/vmops.py:569
#, python-format
msgid ""
"The call to %(method)s returned an error: %(e)s. VM id=%(instance_id)s; "
"args=%(strargs)s"
msgstr ""

#: ../nova/virt/xenapi/vmops.py:1788
#, python-format
msgid "OpenSSL error: %s"
msgstr ""

#: ../nova/tests/test_compute.py:335 ../nova/tests/test_compute.py:1307
#, python-format
msgid "Running instances: %s"
msgstr ""

#: ../nova/tests/test_compute.py:341
#, python-format
msgid "After terminating instances: %s"
msgstr ""

#: ../nova/cloudpipe/pipelib.py:45
msgid "Template for script to run on cloudpipe instance boot"
msgstr ""

#: ../nova/cloudpipe/pipelib.py:48
msgid "Network to push into openvpn config"
msgstr ""

#: ../nova/cloudpipe/pipelib.py:51
msgid "Netmask to push into openvpn config"
msgstr ""

#: ../nova/cloudpipe/pipelib.py:96
#, python-format
msgid "Launching VPN for %s"
msgstr "Executando VPN para %s"

#: ../nova/db/sqlalchemy/migration.py:36
msgid "python-migrate is not installed. Exiting."
msgstr ""

#: ../nova/image/s3.py:99
#, python-format
msgid "Image %s could not be found"
msgstr ""

#: ../nova/api/ec2/__init__.py:134
msgid "Too many failed authentications."
msgstr "Muitas falhas de autenticação."

#: ../nova/api/ec2/__init__.py:144
#, python-format
msgid ""
"Access key %(access_key)s has had %(failures)d failed authentications and "
"will be locked out for %(lock_mins)d minutes."
msgstr ""

#: ../nova/api/ec2/__init__.py:204
#, python-format
msgid "Authentication Failure: %s"
msgstr "Falha de Autenticação: %s"

#: ../nova/api/ec2/__init__.py:220
#, python-format
msgid "Authenticated Request For %(uname)s:%(pname)s)"
msgstr ""

#: ../nova/api/ec2/__init__.py:251
#, python-format
msgid "action: %s"
msgstr "ação: %s"

#: ../nova/api/ec2/__init__.py:253
#, python-format
msgid "arg: %(key)s\t\tval: %(value)s"
msgstr ""

#: ../nova/api/ec2/__init__.py:328
#, python-format
msgid ""
"Unauthorized request for controller=%(controller)s and action=%(action)s"
msgstr ""

#: ../nova/api/ec2/__init__.py:359
#, python-format
msgid "InstanceNotFound raised: %s"
msgstr ""

#: ../nova/api/ec2/__init__.py:365
#, python-format
msgid "VolumeNotFound raised: %s"
msgstr ""

#: ../nova/api/ec2/__init__.py:377
#, python-format
msgid "NotFound raised: %s"
msgstr "NotFound lançado: %s"

#: ../nova/api/ec2/__init__.py:380
#, python-format
msgid "ApiError raised: %s"
msgstr "ApiError lançado: %s"

#: ../nova/api/ec2/__init__.py:409
#, python-format
msgid "Unexpected error raised: %s"
msgstr "Erro inexperado lançado: %s"

#: ../nova/api/metadata/handler.py:253 ../nova/api/ec2/__init__.py:414
msgid "An unknown error has occurred. Please try your request again."
msgstr ""
"Ocorreu um erro desconhecido. Por favor tente sua requisição novamente."

#: ../nova/auth/dbdriver.py:84
#, python-format
msgid "User %s already exists"
msgstr "Usuário %s já existe"

#: ../nova/auth/dbdriver.py:106 ../nova/auth/ldapdriver.py:232
#, python-format
msgid "Project can't be created because manager %s doesn't exist"
msgstr "Projeto não pode ser criado porque o gerente %s não existe."

#: ../nova/auth/dbdriver.py:122 ../nova/auth/ldapdriver.py:243
#, python-format
msgid "Project can't be created because user %s doesn't exist"
msgstr "Projeto não pode ser criado porque o usuário %s não existe"

#: ../nova/auth/dbdriver.py:135 ../nova/auth/ldapdriver.py:229
#, python-format
msgid "Project can't be created because project %s already exists"
msgstr "Projeto não pode ser criado porque o projeto %s já existe."

#: ../nova/auth/dbdriver.py:157 ../nova/auth/ldapdriver.py:268
#, python-format
msgid "Project can't be modified because manager %s doesn't exist"
msgstr "Projeto não pode ser modificado porque o gerente %s não existe."

#: ../nova/auth/dbdriver.py:245
#, python-format
msgid "User \"%s\" not found"
msgstr "Usuário \"%s\" não encontrado"

#: ../nova/auth/dbdriver.py:248
#, python-format
msgid "Project \"%s\" not found"
msgstr "Projeto \"%s\" não encontrado"

#: ../nova/virt/xenapi_conn.py:159
msgid ""
"Must specify xenapi_connection_url, xenapi_connection_username (optionally), "
"and xenapi_connection_password to use connection_type=xenapi"
msgstr ""

#: ../nova/virt/xenapi_conn.py:560
#, python-format
msgid "Task [%(name)s] %(task)s status: success    %(result)s"
msgstr ""

#: ../nova/virt/xenapi_conn.py:569
#, python-format
msgid "Task [%(name)s] %(task)s status: %(status)s    %(error_info)s"
msgstr ""

#: ../nova/virt/xenapi_conn.py:595 ../nova/virt/xenapi_conn.py:608
#, python-format
msgid "Got exception: %s"
msgstr ""

#: ../nova/volume/driver.py:359
#, python-format
msgid "Could not find iSCSI export  for volume %s"
msgstr ""

#: ../nova/api/ec2/apirequest.py:73
#, python-format
msgid ""
"Unsupported API request: controller = %(controller)s, action = %(action)s"
msgstr ""

#: ../nova/api/openstack/v2/__init__.py:61
#, python-format
msgid "Caught error: %s"
msgstr "Capturado o erro: %s"

#: ../nova/api/openstack/v2/__init__.py:113
msgid "Including admin operations in API."
msgstr "Incluindo operações administrativas na API."

#: ../nova/console/xvp.py:93
msgid "Rebuilding xvp conf"
msgstr ""

#: ../nova/console/xvp.py:111
#, python-format
msgid "Re-wrote %s"
msgstr ""

#: ../nova/console/xvp.py:116
msgid "Stopping xvp"
msgstr ""

#: ../nova/console/xvp.py:129
msgid "Starting xvp"
msgstr ""

#: ../nova/console/xvp.py:136
#, python-format
msgid "Error starting xvp: %s"
msgstr ""

#: ../nova/console/xvp.py:139
msgid "Restarting xvp"
msgstr ""

#: ../nova/console/xvp.py:141
msgid "xvp not running..."
msgstr ""

#: ../bin/nova-manage.py:272
msgid ""
"The above error may show that the database has not been created.\n"
"Please create a database using nova-manage sync db before running this "
"command."
msgstr ""

#: ../bin/nova-manage.py:426
msgid ""
"No more networks available. If this is a new installation, you need\n"
"to call something like this:\n"
"\n"
"    nova-manage network create 10.0.0.0/8 10 64\n"
"\n"
msgstr ""

#: ../bin/nova-manage.py:616
msgid ""
"The above error may show that the certificate db has not been created.\n"
"Please create a database by running a nova-api server on this host."
msgstr ""

#: ../bin/nova-manage.py:640
msgid "network"
msgstr ""

#: ../bin/nova-manage.py:641
msgid "IP address"
msgstr ""

#: ../bin/nova-manage.py:642
msgid "MAC address"
msgstr ""

#: ../bin/nova-manage.py:643
msgid "hostname"
msgstr ""

#: ../bin/nova-manage.py:644 ../bin/nova-manage.py:1181
#: ../bin/nova-manage.py:1297 ../bin/nova-manage.py:1329
msgid "host"
msgstr ""

#: ../bin/nova-manage.py:537
msgid "netmask"
msgstr ""

#: ../bin/nova-manage.py:852 ../nova/tests/test_nova_manage.py:183
msgid "start address"
msgstr ""

#: ../nova/virt/disk.py:124
#, python-format
msgid "Failed to load partition: %s"
msgstr ""

#: ../nova/virt/disk/api.py:222 ../nova/virt/disk/guestfs.py:64
#: ../nova/virt/disk/guestfs.py:78 ../nova/virt/disk/mount.py:112
#, python-format
msgid "Failed to mount filesystem: %s"
msgstr ""

#: ../nova/virt/disk/nbd.py:82
#, python-format
msgid "nbd device %s did not show up"
msgstr ""

#: ../nova/virt/disk/loop.py:30
#, python-format
msgid "Could not attach image to loopback: %s"
msgstr ""

#. really want to log this info, not raise
#: ../nova/virt/disk/nbd.py:52
msgid "No free nbd devices"
msgstr ""

#: ../doc/ext/nova_todo.py:46
#, python-format
msgid "%(filename)s, line %(line_info)d"
msgstr ""

#. FIXME(chiradeep): implement this
#: ../nova/virt/hyperv.py:119
msgid "In init host"
msgstr ""

#: ../nova/virt/hyperv.py:131
#, python-format
msgid "Attempt to create duplicate vm %s"
msgstr ""

#: ../nova/virt/hyperv.py:166
#, python-format
msgid "Starting VM %s "
msgstr ""

#: ../nova/virt/hyperv.py:168
#, python-format
msgid "Started VM %s "
msgstr ""

#: ../nova/virt/hyperv.py:170
#, python-format
msgid "spawn vm failed: %s"
msgstr ""

#: ../nova/virt/hyperv.py:187
#, python-format
msgid "Failed to create VM %s"
msgstr ""

#: ../nova/virt/hyperv.py:206
#, python-format
msgid "Set memory for vm %s..."
msgstr ""

#: ../nova/virt/hyperv.py:216
#, python-format
msgid "Set vcpus for vm %s..."
msgstr ""

#: ../nova/virt/hyperv.py:220
#, python-format
msgid "Creating disk for %(vm_name)s by attaching disk file %(vhdfile)s"
msgstr ""

#: ../nova/virt/hyperv.py:245
#, python-format
msgid "Failed to add diskdrive to VM %s"
msgstr ""

#: ../nova/virt/hyperv.py:248
#, python-format
msgid "New disk drive path is %s"
msgstr ""

#: ../nova/virt/hyperv.py:265
#, python-format
msgid "Failed to add vhd file to VM %s"
msgstr ""

#: ../nova/virt/hyperv.py:267
#, python-format
msgid "Created disk for %s"
msgstr ""

#: ../nova/virt/hyperv.py:271
#, python-format
msgid "Creating nic for %s "
msgstr ""

#: ../nova/virt/hyperv.py:290
msgid "Failed creating a port on the external vswitch"
msgstr ""

#: ../nova/virt/hyperv.py:291
#, python-format
msgid "Failed creating port for %s"
msgstr ""

#: ../nova/virt/hyperv.py:294
#, python-format
msgid "Created switch port %(vm_name)s on switch %(ext_path)s"
msgstr ""

#: ../nova/virt/hyperv.py:304
#, python-format
msgid "Failed to add nic to VM %s"
msgstr ""

#: ../nova/virt/hyperv.py:306
#, python-format
msgid "Created nic for %s "
msgstr ""

#: ../nova/virt/hyperv.py:339
#, python-format
msgid "WMI job failed: %s"
msgstr ""

#: ../nova/virt/hyperv.py:343
#, python-format
msgid "WMI job succeeded: %(desc)s, Elapsed=%(elap)s "
msgstr ""

#: ../nova/virt/hyperv.py:379
#, python-format
msgid "Got request to destroy vm %s"
msgstr ""

#: ../nova/virt/hyperv.py:404
#, python-format
msgid "Failed to destroy vm %s"
msgstr ""

#: ../nova/virt/hyperv.py:411
#, python-format
msgid "Del: disk %(vhdfile)s vm %(instance_name)s"
msgstr ""

#: ../nova/virt/hyperv.py:433
#, python-format
msgid ""
"Got Info for vm %(instance_id)s: state=%(state)s, mem=%(memusage)s, "
"num_cpu=%(numprocs)s, cpu_time=%(uptime)s"
msgstr ""

#: ../nova/virt/hyperv.py:469
#, python-format
msgid "Successfully changed vm state of %(vm_name)s to %(req_state)s"
msgstr ""

#: ../nova/virt/hyperv.py:472
#, python-format
msgid "Failed to change vm state of %(vm_name)s to %(req_state)s"
msgstr ""

#: ../nova/compute/api.py:71
#, python-format
msgid "Instance %d was not found in get_network_topic"
msgstr ""

#: ../nova/compute/api.py:77
#, python-format
msgid "Instance %d has no host"
msgstr ""

#: ../nova/compute/api.py:97
#, python-format
msgid "Quota exceeeded for %(pid)s, tried to run %(min_count)s instances"
msgstr ""

#: ../nova/compute/api.py:219
#, python-format
msgid ""
"Instance quota exceeded. You can only run %s more instances of this type."
msgstr ""

#: ../nova/compute/api.py:268
msgid "Creating a raw instance"
msgstr ""

#: ../nova/compute/api.py:323
#, python-format
msgid "Going to run %s instances..."
msgstr ""

#: ../nova/compute/api.py:187
#, python-format
msgid "Casting to scheduler for %(pid)s/%(uid)s's instance %(instance_id)s"
msgstr ""

#: ../nova/compute/api.py:852
#, python-format
msgid "Going to try to terminate %s"
msgstr ""

#: ../nova/compute/api.py:296
#, python-format
msgid "Instance %d was not found during terminate"
msgstr ""

#: ../nova/compute/api.py:301
#, python-format
msgid "Instance %d is already being terminated"
msgstr ""

#: ../nova/compute/api.py:1644
#, python-format
msgid "Invalid device specified: %s. Example device: /dev/vdb"
msgstr ""

#: ../nova/compute/api.py:1659
msgid "Volume isn't attached to anything!"
msgstr ""

#: ../nova/rpc.py:98
#, python-format
msgid ""
"AMQP server on %(fl_host)s:%(fl_port)d is unreachable. Trying again in "
"%(fl_intv)d seconds."
msgstr ""

#: ../nova/rpc.py:103
#, python-format
msgid "Unable to connect to AMQP server after %d tries. Shutting down."
msgstr ""
"Não foi possível conectar ao servidor AMQP após %d tentativas. Desligando."

#: ../nova/rpc/impl_carrot.py:221
msgid "Reconnected to queue"
msgstr "Reconectado à fila"

#: ../nova/rpc.py:129
msgid "Failed to fetch message from queue"
msgstr "Falha ao obter mensagem da fila"

#: ../nova/rpc/impl_carrot.py:236
#, python-format
msgid "Initing the Adapter Consumer for %s"
msgstr "Iniciando o Adaptador Consumidor para %s"

#: ../nova/rpc/impl_kombu.py:629 ../nova/rpc/impl_carrot.py:256
#, python-format
msgid "received %s"
msgstr "recebido %s"

#. NOTE(vish): we may not want to ack here, but that means that bad
#. messages stay in the queue indefinitely, so for now
#. we just log the message and send an error string
#. back to the caller
#: ../nova/rpc/impl_kombu.py:634 ../nova/rpc/impl_carrot.py:269
#, python-format
msgid "no method for message: %s"
msgstr "sem método para mensagem: %s"

#: ../nova/rpc/impl_kombu.py:635 ../nova/rpc/impl_carrot.py:271
#, python-format
msgid "No method for message: %s"
msgstr "Sem método para mensagem: %s"

#: ../nova/rpc/impl_kombu.py:816 ../nova/rpc/impl_carrot.py:455
#, python-format
msgid "Returning exception %s to caller"
msgstr "Retornando exceção %s ao método de origem"

#: ../nova/rpc/impl_kombu.py:675 ../nova/rpc/impl_carrot.py:488
#, python-format
msgid "unpacked context: %s"
msgstr "conteúdo descompactado: %s"

#: ../nova/rpc.py:313
msgid "Making asynchronous call..."
msgstr "Fazendo chamada assíncrona..."

#: ../nova/rpc/impl_kombu.py:762 ../nova/rpc/impl_carrot.py:524
#, python-format
msgid "MSG_ID is %s"
msgstr "MSG_ID é %s"

#: ../nova/rpc.py:354
msgid "Making asynchronous cast..."
msgstr ""

#: ../nova/rpc/impl_carrot.py:634
#, python-format
msgid "response %s"
msgstr "resposta %s"

#: ../nova/rpc/impl_carrot.py:643
#, python-format
msgid "topic is %s"
msgstr "topico é %s"

#: ../nova/rpc/impl_carrot.py:644
#, python-format
msgid "message %s"
msgstr "mensagem %s"

#: ../nova/volume/driver.py:79
#, python-format
msgid "Recovering from a failed execute.  Try number %s"
msgstr ""

#: ../nova/volume/driver.py:89
#, python-format
msgid "volume group %s doesn't exist"
msgstr ""

#: ../nova/volume/driver.py:342
#, python-format
msgid "FAKE AOE: %s"
msgstr ""

#: ../nova/volume/driver.py:251 ../nova/volume/driver.py:847
msgid "Skipping ensure_export. No iscsi_target "
msgstr ""

#: ../nova/volume/driver.py:295 ../nova/volume/driver.py:304
#: ../nova/volume/driver.py:891
msgid "Skipping remove_export. No iscsi_target "
msgstr ""

#: ../nova/volume/driver.py:463
#, python-format
msgid "FAKE ISCSI: %s"
msgstr ""

#: ../nova/volume/driver.py:475
#, python-format
msgid "rbd has no pool %s"
msgstr ""

#: ../nova/volume/driver.py:545
#, python-format
msgid "Sheepdog is not working: %s"
msgstr ""

#: ../nova/volume/driver.py:547
msgid "Sheepdog is not working"
msgstr ""

#: ../nova/wsgi.py:68
#, python-format
msgid "Starting %(arg0)s on %(host)s:%(port)s"
msgstr ""

#: ../nova/wsgi.py:204
msgid "You must implement __call__"
msgstr ""

#: ../bin/nova-dhcpbridge.py:54
msgid "leasing ip"
msgstr ""

#: ../bin/nova-dhcpbridge.py:73
msgid "Adopted old lease or got a change of mac/hostname"
msgstr ""

#: ../bin/nova-dhcpbridge.py:74
msgid "releasing ip"
msgstr ""

#: ../bin/nova-dhcpbridge.py:123
#, python-format
msgid ""
"Called %(action)s for mac %(mac)s with ip %(ip)s and hostname %(hostname)s "
"on interface %(interface)s"
msgstr ""

#: ../nova/virt/fake.py:239
#, python-format
msgid "Instance %s Not Found"
msgstr ""

#: ../nova/network/manager.py:386
#, python-format
msgid "Dissassociated %s stale fixed ip(s)"
msgstr ""

#: ../nova/network/manager.py:564
msgid "setting network host"
msgstr ""

#: ../nova/network/manager.py:212
#, python-format
msgid "Leasing IP %s"
msgstr ""

#: ../nova/network/manager.py:216
#, python-format
msgid "IP %s leased that isn't associated"
msgstr ""

#: ../nova/network/manager.py:220
#, python-format
msgid "IP %(address)s leased to bad mac %(inst_addr)s vs %(mac)s"
msgstr ""

#: ../nova/network/manager.py:228
#, python-format
msgid "IP %s leased that was already deallocated"
msgstr ""

#: ../nova/network/manager.py:233
#, python-format
msgid "Releasing IP %s"
msgstr ""

#: ../nova/network/manager.py:237
#, python-format
msgid "IP %s released that isn't associated"
msgstr ""

#: ../nova/network/manager.py:241
#, python-format
msgid "IP %(address)s released from bad mac %(inst_addr)s vs %(mac)s"
msgstr ""

#: ../nova/network/manager.py:1063
#, python-format
msgid "IP %s released that was not leased"
msgstr ""

#: ../nova/network/manager.py:1490
msgid ""
"The sum between the number of networks and the vlan start cannot be greater "
"than 4094"
msgstr ""

#: ../nova/virt/xenapi/volume_utils.py:157
#, python-format
msgid "Introducing %s..."
msgstr ""

#: ../nova/virt/xenapi/volume_utils.py:103
#: ../nova/virt/xenapi/volume_utils.py:170
#: ../nova/virt/xenapi/volumeops.py:157
#, python-format
msgid "Introduced %(label)s as %(sr_ref)s."
msgstr ""

#: ../nova/virt/xenapi/volume_utils.py:76
#: ../nova/virt/xenapi/volume_utils.py:174
msgid "Unable to create Storage Repository"
msgstr ""

#: ../nova/virt/xenapi/volume_utils.py:186
#, python-format
msgid "Unable to find SR from VBD %s"
msgstr ""

#: ../nova/virt/xenapi/volume_utils.py:96
#, python-format
msgid "Forgetting SR %s ... "
msgstr ""

#: ../nova/virt/xenapi/volume_utils.py:228
#, python-format
msgid "Ignoring exception %(exc)s when getting PBDs for %(sr_ref)s"
msgstr ""

#: ../nova/virt/xenapi/volume_utils.py:234
#, python-format
msgid "Ignoring exception %(exc)s when unplugging PBD %(pbd)s"
msgstr ""

#: ../nova/virt/xenapi/volume_utils.py:111
#, python-format
msgid "Forgetting SR %s done."
msgstr ""

#: ../nova/virt/xenapi/volume_utils.py:113
#, python-format
msgid "Ignoring exception %(exc)s when forgetting SR %(sr_ref)s"
msgstr ""

#: ../nova/virt/xenapi/volume_utils.py:249
#, python-format
msgid "Unable to introduce VDI on SR %s"
msgstr ""

#: ../nova/virt/xenapi/volume_utils.py:257
#, python-format
msgid "Unable to get record of VDI %s on"
msgstr ""

#: ../nova/virt/xenapi/volume_utils.py:279
#, python-format
msgid "Unable to introduce VDI for SR %s"
msgstr ""

#: ../nova/virt/xenapi/volume_utils.py:175
#, python-format
msgid "Unable to obtain target information %(device_path)s, %(mountpoint)s"
msgstr ""

#: ../nova/virt/xenapi/volume_utils.py:356
#, python-format
msgid "Mountpoint cannot be translated: %s"
msgstr ""

#: ../nova/image/s3.py:365
#, python-format
msgid "Failed to decrypt private key: %s"
msgstr ""

#: ../nova/image/s3.py:374
#, python-format
msgid "Failed to decrypt initialization vector: %s"
msgstr ""

#: ../nova/image/s3.py:385
#, python-format
msgid "Failed to decrypt image file %(image_file)s: %(err)s"
msgstr ""

#: ../nova/objectstore/handler.py:106
#, python-format
msgid "Unknown S3 value type %r"
msgstr ""

#: ../nova/objectstore/handler.py:137
msgid "Authenticated request"
msgstr ""

#: ../nova/objectstore/handler.py:182
msgid "List of buckets requested"
msgstr ""

#: ../nova/objectstore/handler.py:209
#, python-format
msgid "List keys for bucket %s"
msgstr ""

#: ../nova/objectstore/handler.py:217
#, python-format
msgid "Unauthorized attempt to access bucket %s"
msgstr ""

#: ../nova/objectstore/handler.py:235
#, python-format
msgid "Creating bucket %s"
msgstr ""

#: ../nova/objectstore/handler.py:245
#, python-format
msgid "Deleting bucket %s"
msgstr ""

#: ../nova/objectstore/handler.py:249
#, python-format
msgid "Unauthorized attempt to delete bucket %s"
msgstr ""

#: ../nova/objectstore/handler.py:273
#, python-format
msgid "Getting object: %(bname)s / %(nm)s"
msgstr ""

#: ../nova/objectstore/handler.py:276
#, python-format
msgid "Unauthorized attempt to get object %(nm)s from bucket %(bname)s"
msgstr ""

#: ../nova/objectstore/handler.py:296
#, python-format
msgid "Putting object: %(bname)s / %(nm)s"
msgstr ""

#: ../nova/objectstore/handler.py:299
#, python-format
msgid "Unauthorized attempt to upload object %(nm)s to bucket %(bname)s"
msgstr ""

#: ../nova/objectstore/handler.py:318
#, python-format
msgid "Deleting object: %(bname)s / %(nm)s"
msgstr ""

#: ../nova/objectstore/handler.py:322
#, python-format
msgid "Unauthorized attempt to delete object %(nm)s from bucket %(bname)s"
msgstr ""

#: ../nova/objectstore/handler.py:396
#, python-format
msgid "Not authorized to upload image: invalid directory %s"
msgstr ""

#: ../nova/objectstore/handler.py:404
#, python-format
msgid "Not authorized to upload image: unauthorized bucket %s"
msgstr ""

#: ../nova/objectstore/handler.py:409
#, python-format
msgid "Starting image upload: %s"
msgstr ""

#: ../nova/objectstore/handler.py:423
#, python-format
msgid "Not authorized to update attributes of image %s"
msgstr ""

#: ../nova/objectstore/handler.py:431
#, python-format
msgid "Toggling publicity flag of image %(image_id)s %(newstatus)r"
msgstr ""

#. other attributes imply update
#: ../nova/objectstore/handler.py:436
#, python-format
msgid "Updating user fields on image %s"
msgstr ""

#: ../nova/objectstore/handler.py:450
#, python-format
msgid "Unauthorized attempt to delete image %s"
msgstr ""

#: ../nova/objectstore/handler.py:455
#, python-format
msgid "Deleted image: %s"
msgstr ""

#: ../nova/auth/manager.py:277
#, python-format
msgid "Looking up user: %r"
msgstr "Procurando usuário: %r"

#: ../nova/auth/manager.py:281
#, python-format
msgid "Failed authorization for access key %s"
msgstr "Falha de autorização para chave de acesso %s"

#: ../nova/auth/manager.py:264
#, python-format
msgid "No user found for access key %s"
msgstr "Nenhum usuário encontrado para chave de acesso %s"

#: ../nova/auth/manager.py:287
#, python-format
msgid "Using project name = user name (%s)"
msgstr "Usando nome do projeto = nome do usuário (%s)"

#: ../nova/auth/manager.py:294
#, python-format
msgid "failed authorization: no project named %(pjid)s (user=%(uname)s)"
msgstr ""

#: ../nova/auth/manager.py:279
#, python-format
msgid "No project called %s could be found"
msgstr "Nenhum projeto chamado %s pode ser encontrado."

#: ../nova/auth/manager.py:303
#, python-format
msgid ""
"Failed authorization: user %(uname)s not admin and not member of project "
"%(pjname)s"
msgstr ""

#: ../nova/auth/manager.py:289
#, python-format
msgid "User %(uid)s is not a member of project %(pjid)s"
msgstr ""

#: ../nova/auth/manager.py:314 ../nova/auth/manager.py:336
#, python-format
msgid "Invalid signature for user %s"
msgstr "Assinatura inválida para usuário %s"

#: ../nova/auth/manager.py:299 ../nova/auth/manager.py:310
msgid "Signature does not match"
msgstr "Assinatura não confere"

#: ../nova/auth/manager.py:428
msgid "Must specify project"
msgstr "Deve especificar projeto"

#: ../nova/auth/manager.py:414
#, python-format
msgid "The %s role can not be found"
msgstr "O papel %s não foi encontrado"

#: ../nova/auth/manager.py:416
#, python-format
msgid "The %s role is global only"
msgstr "O papel %s é apenas global"

#: ../nova/auth/manager.py:469
#, python-format
msgid "Adding role %(role)s to user %(uid)s in project %(pid)s"
msgstr ""

#: ../nova/auth/manager.py:472
#, python-format
msgid "Adding sitewide role %(role)s to user %(uid)s"
msgstr ""

#: ../nova/auth/manager.py:498
#, python-format
msgid "Removing role %(role)s from user %(uid)s on project %(pid)s"
msgstr ""

#: ../nova/auth/manager.py:501
#, python-format
msgid "Removing sitewide role %(role)s from user %(uid)s"
msgstr ""

#: ../nova/auth/manager.py:574
#, python-format
msgid "Created project %(name)s with manager %(manager_user)s"
msgstr ""

#: ../nova/auth/manager.py:592
#, python-format
msgid "modifying project %s"
msgstr "modificando projeto %s"

#: ../nova/auth/manager.py:604
#, python-format
msgid "Adding user %(uid)s to project %(pid)s"
msgstr ""

#: ../nova/auth/manager.py:625
#, python-format
msgid "Remove user %(uid)s from project %(pid)s"
msgstr ""

#: ../nova/auth/manager.py:655
#, python-format
msgid "Deleting project %s"
msgstr "Excluindo projeto %s"

#: ../nova/auth/manager.py:713
#, python-format
msgid "Created user %(rvname)s (admin: %(rvadmin)r)"
msgstr ""

#: ../nova/auth/manager.py:722
#, python-format
msgid "Deleting user %s"
msgstr "Apagando usuário %s"

#: ../nova/auth/manager.py:732
#, python-format
msgid "Access Key change for user %s"
msgstr ""

#: ../nova/auth/manager.py:734
#, python-format
msgid "Secret Key change for user %s"
msgstr ""

#: ../nova/auth/manager.py:736
#, python-format
msgid "Admin status set to %(admin)r for user %(uid)s"
msgstr ""

#: ../nova/auth/manager.py:781
#, python-format
msgid "No vpn data for project %s"
msgstr ""

#: ../nova/service.py:141
#, python-format
msgid "Starting %(topic)s node (version %(vcs_string)s)"
msgstr ""

#: ../nova/service.py:232
msgid "Service killed that has no database entry"
msgstr "Encerrado serviço que não tem entrada na base de dados"

#: ../nova/service.py:269
msgid "The service database object disappeared, Recreating it."
msgstr "O objeto da base de dados do serviço desapareceu, Recriando."

#: ../nova/service.py:284
msgid "Recovered model server connection!"
msgstr "Recuperada conexão servidor de modelo."

#: ../nova/service.py:290
msgid "model server went away"
msgstr "servidor de modelo perdido"

#: ../nova/auth/ldapdriver.py:174
#, python-format
msgid "LDAP user %s already exists"
msgstr "Usuário LDAP %s já existe"

#: ../nova/auth/ldapdriver.py:205
#, python-format
msgid "LDAP object for %s doesn't exist"
msgstr "Objeto LDAP para %s não existe"

#: ../nova/auth/ldapdriver.py:348
#, python-format
msgid "User %s doesn't exist"
msgstr ""

#: ../nova/auth/ldapdriver.py:472
#, python-format
msgid "Group can't be created because group %s already exists"
msgstr "Grupo não pode ser criado porque o grupo %s já existe"

#: ../nova/auth/ldapdriver.py:478
#, python-format
msgid "Group can't be created because user %s doesn't exist"
msgstr "Grupo não pode ser criado porque o usuário %s não existe"

#: ../nova/auth/ldapdriver.py:495
#, python-format
msgid "User %s can't be searched in group because the user doesn't exist"
msgstr ""
"Usuário %s não pode ser pesquisado no grupo porque o usuário não existe"

#: ../nova/auth/ldapdriver.py:507
#, python-format
msgid "User %s can't be added to the group because the user doesn't exist"
msgstr ""
"Usuário %s não pode ser adicionado no grupo porque o usuário não existe"

#: ../nova/auth/ldapdriver.py:510 ../nova/auth/ldapdriver.py:521
#, python-format
msgid "The group at dn %s doesn't exist"
msgstr "O grupo no dn %s não existe"

#: ../nova/exception.py:801
#, python-format
msgid "User %(uid)s is already a member of the group %(group_dn)s"
msgstr "Usuário %(uid)s já é um membro do grupo %(group_dn)s"

#: ../nova/auth/ldapdriver.py:524
#, python-format
msgid ""
"User %s can't be removed from the group because the user doesn't exist"
msgstr ""
"Usuário %s não pode ser removido do grupo porque o usuário não existe"

#: ../nova/auth/ldapdriver.py:528
#, python-format
msgid "User %s is not a member of the group"
msgstr "Usuário %s não é um membro do grupo"

#: ../nova/auth/ldapdriver.py:621
#, python-format
msgid ""
"Attempted to remove the last member of a group. Deleting the group at %s "
"instead."
msgstr ""
"Tentatica de remover o último membto de um grupo. Ao invés disso excluindo o "
"grupo %s."

#: ../nova/auth/ldapdriver.py:549
#, python-format
msgid "User %s can't be removed from all because the user doesn't exist"
msgstr "Usuário %s não pode ser removido de tudo porque o usuário não existe"

#: ../nova/auth/ldapdriver.py:564
#, python-format
msgid "Group at dn %s doesn't exist"
msgstr "Grupo no dn %s não existe"

#: ../nova/virt/xenapi/network_utils.py:55
#, python-format
msgid "Found non-unique network for bridge %s"
msgstr "Encontrado múltiplas redes para a bridge %s"

#: ../nova/virt/xenapi/network_utils.py:58
#, python-format
msgid "Found no network for bridge %s"
msgstr "Não foi encontrada rede para bridge %s"

#: ../nova/api/ec2/admin.py:146
#, python-format
msgid "Creating new user: %s"
msgstr "Criando novo usuário: %s"

#: ../nova/api/ec2/admin.py:154
#, python-format
msgid "Deleting user: %s"
msgstr "Excluindo usuário: %s"

#: ../nova/api/ec2/admin.py:176
#, python-format
msgid "Adding role %(role)s to user %(user)s for project %(project)s"
msgstr ""
"Adicionando função %(role)s para usuário %(user)s no projeto %(project)s"

#: ../nova/api/ec2/admin.py:180
#, python-format
msgid "Adding sitewide role %(role)s to user %(user)s"
msgstr ""

#: ../nova/api/ec2/admin.py:186
#, python-format
msgid "Removing role %(role)s from user %(user)s for project %(project)s"
msgstr "Removendo função %(role)s do usuário %(user)s no projeto %(project)s"

#: ../nova/api/ec2/admin.py:190
#, python-format
msgid "Removing sitewide role %(role)s from user %(user)s"
msgstr ""

#: ../nova/api/ec2/admin.py:195 ../nova/api/ec2/admin.py:272
msgid "operation must be add or remove"
msgstr "operações devem ser adicionar e excluir"

#: ../nova/api/ec2/admin.py:208
#, python-format
msgid "Getting x509 for user: %(name)s on project: %(project)s"
msgstr "Obtendo x509 para usuário: %(name)s no projeto: %(project)s"

#: ../nova/api/ec2/admin.py:226
#, python-format
msgid "Create project %(name)s managed by %(manager_user)s"
msgstr "Criado projeto %(name)s gerenciado por %(manager_user)s"

#: ../nova/api/ec2/admin.py:239
#, python-format
msgid "Modify project: %(name)s managed by %(manager_user)s"
msgstr "Modifique o projeto: %(name)s gerenciado por %(manager_user)s"

#: ../nova/api/ec2/admin.py:249
#, python-format
msgid "Delete project: %s"
msgstr "Excluir projeto: %s"

#: ../nova/api/ec2/admin.py:263
#, python-format
msgid "Adding user %(user)s to project %(project)s"
msgstr "Adicionando usuário %(user)s no projeto %(project)s"

#: ../nova/api/ec2/admin.py:267
#, python-format
msgid "Removing user %(user)s from project %(project)s"
msgstr "Removendo usuário %(user)s do projeto %(project)s"

#~ msgid "Full set of FLAGS:"
#~ msgstr "Conjunto completo de FLAGS:"

#, python-format
#~ msgid "Starting %s"
#~ msgstr "Iniciando %s"

#, python-format
#~ msgid "Serving %s"
#~ msgstr "Servindo %s"

#~ msgid "No such process"
#~ msgstr "Processo inexistente"

#, python-format
#~ msgid "pidfile %s does not exist. Daemon not running?\n"
#~ msgstr ""
#~ "Arquivo do id do processo (pidfile) %s não existe. O Daemon está parado?\n"

#~ msgid "Wrong number of arguments."
#~ msgstr "Número errado de argumentos."
