# Chinese (Simplified) translation for nova
# Copyright (c) 2011 Rosetta Contributors and Canonical Ltd 2011
# This file is distributed under the same license as the nova package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2011.
#
msgid ""
msgstr ""
"Project-Id-Version: nova\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2011-02-21 10:03-0500\n"
"PO-Revision-Date: 2011-12-09 11:53+0000\n"
"Last-Translator: xh2012@gmail.com <Unknown>\n"
"Language-Team: Chinese (Simplified) <zh_CN@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2011-12-10 05:25+0000\n"
"X-Generator: Launchpad (build 14450)\n"

#, python-format
#~ msgid "Starting %s"
#~ msgstr "启动 %s 中"

#: ../nova/scheduler/chance.py:37 ../nova/scheduler/zone.py:55
#: ../nova/scheduler/simple.py:75 ../nova/scheduler/simple.py:110
#: ../nova/scheduler/simple.py:122
msgid "No hosts found"
msgstr "没有找到主机"

#: ../nova/exception.py:54
msgid "Unexpected error while running command."
msgstr "运行命令时出现错误"

#: ../nova/exception.py:57
#, python-format
msgid ""
"%(description)s\n"
"Command: %(cmd)s\n"
"Exit code: %(exit_code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"
msgstr ""
"%(description)s\n"
"命令: %(cmd)s\n"
"退出代码: %(exit_code)s\n"
"标准输出: %(stdout)r\n"
"标准出错: %(stderr)r"

#: ../nova/exception.py:107
msgid "DB exception wrapped"
msgstr "数据库异常"

#. exc_type, exc_value, exc_traceback = sys.exc_info()
#: ../nova/exception.py:127
msgid "Uncaught exception"
msgstr "未捕获异常"

#: ../nova/volume/api.py:45
#, python-format
msgid "Quota exceeeded for %(pid)s, tried to create %(size)sG volume"
msgstr "%(pid)s 超出配额，产生创建%(size)sG卷"

#: ../nova/volume/api.py:57
#, python-format
msgid "Volume quota exceeded. You cannot create a volume of size %sG"
msgstr "卷磁盘配额已耗尽，不能创建 %sG 大小的卷"

#: ../nova/volume/api.py:102 ../nova/volume/api.py:172
#: ../nova/volume/api.py:230
msgid "Volume status must be available"
msgstr "卷组状态必须可获取"

#: ../nova/volume/api.py:174
msgid "Volume is already attached"
msgstr "卷已挂载"

#: ../nova/volume/api.py:180
msgid "Volume is already detached"
msgstr "卷已卸载"

#: ../nova/api/openstack/servers.py:72
msgid "Failed to read private ip"
msgstr "获取内网IP失败"

#: ../nova/api/openstack/servers.py:79
msgid "Failed to read public ip(s)"
msgstr "获取外网IP失败"

#: ../nova/api/openstack/servers.py:152
#, python-format
msgid "%(param)s property not found for image %(_image_id)s"
msgstr "没有找到镜像文件%(_image_id)s 的属性 %(param)s"

#: ../nova/api/openstack/servers.py:168
msgid "No keypairs defined"
msgstr "未定义密钥对"

#: ../nova/api/openstack/v2/contrib/admin_actions.py:165
#, python-format
msgid "Compute.api::lock %s"
msgstr "compute.api::加锁 %s"

#: ../nova/api/openstack/v2/contrib/admin_actions.py:182
#, python-format
msgid "Compute.api::unlock %s"
msgstr "compute.api::解锁 %s"

#: ../nova/api/openstack/servers.py:388
#, python-format
msgid "Compute.api::get_lock %s"
msgstr "Compute.api::得到锁 %s"

#: ../nova/api/openstack/v2/contrib/admin_actions.py:131
#, python-format
msgid "Compute.api::reset_network %s"
msgstr "Compute.api::重置网络 %s"

#: ../nova/api/openstack/v2/contrib/admin_actions.py:59
#, python-format
msgid "Compute.api::pause %s"
msgstr "Compute.api::暂停 %s"

#: ../nova/api/openstack/v2/contrib/admin_actions.py:74
#, python-format
msgid "Compute.api::unpause %s"
msgstr "Compute.api::继续 %s"

#: ../nova/api/openstack/v2/contrib/admin_actions.py:89
#, python-format
msgid "compute.api::suspend %s"
msgstr "compute.api::挂起 %s"

#: ../nova/api/openstack/v2/contrib/admin_actions.py:104
#, python-format
msgid "compute.api::resume %s"
msgstr "compute.api::回复 %s"

#: ../nova/virt/xenapi/volumeops.py:48 ../nova/virt/xenapi/volumeops.py:101
#: ../nova/db/sqlalchemy/api.py:731 ../nova/virt/libvirt_conn.py:741
#: ../nova/api/ec2/__init__.py:317
#, python-format
msgid "Instance %s not found"
msgstr "实例 %s 没有找到"

#. NOTE: No Resource Pool concept so far
#: ../nova/virt/xenapi/volumeops.py:50
#, python-format
msgid "Attach_volume: %(instance_name)s, %(device_path)s, %(mountpoint)s"
msgstr "挂载卷：%(instance_name)s, %(device_path)s, %(mountpoint)s"

#: ../nova/virt/xenapi/volumeops.py:174
#, python-format
msgid "Unable to create VDI on SR %(sr_ref)s for instance %(instance_name)s"
msgstr "无法在SR %(sr_ref)s 上为实例 %(instance_name)s 创建 VDI"

#: ../nova/virt/xenapi/volumeops.py:187
#, python-format
msgid "Unable to use SR %(sr_ref)s for instance %(instance_name)s"
msgstr "不能为实例%(instance_name)s使用SR %(sr_ref)s"

#: ../nova/virt/xenapi/volumeops.py:195
#, python-format
msgid "Unable to attach volume to instance %s"
msgstr "无法挂载卷到虚拟机 %s"

#: ../nova/virt/xenapi/volumeops.py:198
#, python-format
msgid "Mountpoint %(mountpoint)s attached to instance %(instance_name)s"
msgstr "挂载点 %(mountpoint)s 挂载到虚拟机 %(instance_name)s"

#. Detach VBD from VM
#: ../nova/virt/xenapi/volumeops.py:208
#, python-format
msgid "Detach_volume: %(instance_name)s, %(mountpoint)s"
msgstr "卸载_volume: %(instance_name)s, %(mountpoint)s"

#: ../nova/virt/xenapi/volumeops.py:216
#, python-format
msgid "Unable to locate volume %s"
msgstr "无法找到 %s 卷"

#: ../nova/virt/xenapi/volumeops.py:224
#, python-format
msgid "Unable to detach volume %s"
msgstr "无法卸载 %s 卷"

#: ../nova/virt/xenapi/volumeops.py:238
#, python-format
msgid "Mountpoint %(mountpoint)s detached from instance %(instance_name)s"
msgstr "挂载点 %(mountpoint)s 从虚拟机 %(instance_name)s 卸载"

#: ../nova/compute/instance_types.py:115 ../nova/compute/instance_types.py:127
#: ../nova/compute/instance_types.py:141 ../nova/compute/instance_types.py:152
#, python-format
msgid "Unknown instance type: %s"
msgstr "未知的虚拟机类型：%s"

#: ../nova/crypto.py:50
msgid "Filename of root CA"
msgstr "根证书文件名"

#: ../nova/crypto.py:53
msgid "Filename of private key"
msgstr "私钥文件名"

#: ../nova/crypto.py:55
msgid "Filename of root Certificate Revokation List"
msgstr "已废除的根证书列表"

#: ../nova/crypto.py:57
msgid "Where we keep our keys"
msgstr "保存密钥的位置"

#: ../nova/crypto.py:59
msgid "Where we keep our root CA"
msgstr "保存根证书的位置"

#: ../nova/crypto.py:61
msgid "Should we use a CA for each project?"
msgstr "是否所有项目都是用证书授权（CA）？"

#: ../nova/crypto.py:65
#, python-format
msgid "Subject for certificate for users, %s for project, user, timestamp"
msgstr "用户证书的标题，%s依次分别为项目，用户，时间戳"

#: ../nova/crypto.py:70
#, python-format
msgid "Subject for certificate for projects, %s for project, timestamp"
msgstr "项目证书的标题，%s依次分别为项目，时间戳"

#: ../nova/crypto.py:75
#, python-format
msgid "Subject for certificate for vpns, %s for project, timestamp"
msgstr "VPN证书的标题，%s依次分别为项目，时间戳"

#: ../nova/crypto.py:277
#, python-format
msgid "Flags path: %s"
msgstr "Flag所在路径：%s"

#: ../nova/scheduler/manager.py:69
#, python-format
msgid "Casting to %(topic)s %(host)s for %(method)s"
msgstr ""

#: ../nova/compute/manager.py:101
#, python-format
msgid "check_instance_lock: decorating: |%s|"
msgstr ""

#: ../nova/compute/manager.py:104
#, python-format
msgid ""
"check_instance_lock: arguments: |%(self)s| |%(context)s| |%(instance_id)s|"
msgstr ""

#: ../nova/compute/manager.py:107
#, python-format
msgid "check_instance_lock: locked: |%s|"
msgstr "check_instance_lock: 被鎖定: |%s|"

#: ../nova/compute/manager.py:109
#, python-format
msgid "check_instance_lock: admin: |%s|"
msgstr ""

#: ../nova/compute/manager.py:114
#, python-format
msgid "check_instance_lock: executing: |%s|"
msgstr "check_instance_lock: 执行中: |%s|"

#: ../nova/compute/manager.py:118
#, python-format
msgid "check_instance_lock: not executing |%s|"
msgstr ""

#: ../nova/compute/manager.py:334
msgid "Instance has already been created"
msgstr "虚拟机已经创建"

#: ../nova/compute/manager.py:391
#, python-format
msgid "instance %s: starting..."
msgstr "虚拟机 %s ：启动"

#: ../nova/virt/xenapi/vmops.py:216
#, python-format
msgid "instance %s: Failed to spawn"
msgstr ""

#: ../nova/compute/manager.py:233 ../nova/tests/test_cloud.py:286
#, python-format
msgid "Terminating instance %s"
msgstr "正在结束实例 %s"

#: ../nova/compute/manager.py:255
#, python-format
msgid "Deallocating address %s"
msgstr "取消分配地址 %s"

#: ../nova/compute/manager.py:524
#, python-format
msgid "trying to destroy already destroyed instance: %s"
msgstr "尝试销毁已经销毁的实例: %s"

#: ../nova/compute/manager.py:675
#, python-format
msgid "Rebooting instance %s"
msgstr "重启虚拟机 %s"

#: ../nova/compute/manager.py:599
#, python-format
msgid ""
"trying to reboot a non-running instance: %(instance_id)s (state: %(state)s "
"expected: %(running)s)"
msgstr "尝试重启没有在运行中实例: %(instance_id)s (状态: %(state)s 预料: %(running)s)"

#: ../nova/compute/manager.py:734
#, python-format
msgid "instance %s: snapshotting"
msgstr "实例 %s: 快照中"

#: ../nova/compute/manager.py:651
#, python-format
msgid ""
"trying to snapshot a non-running instance: %(instance_id)s (state: %(state)s "
"expected: %(running)s)"
msgstr ""

#: ../nova/compute/manager.py:332
#, python-format
msgid ""
"trying to reset the password on a non-running instance: %(instance_id)s "
"(state: %(instance_state)s expected: %(expected_state)s)"
msgstr ""
"尝试对没有在运行的实例重置密码: %(instance_id)s (状态: %(instance_state)s 预料: "
"%(expected_state)s)"

#: ../nova/compute/manager.py:335
#, python-format
msgid "instance %s: setting admin password"
msgstr "虚拟机 %s：设置管理员密码"

#: ../nova/compute/manager.py:772
#, python-format
msgid ""
"trying to inject a file into a non-running instance: %(instance_id)s (state: "
"%(instance_state)s expected: %(expected_state)s)"
msgstr ""

#: ../nova/compute/manager.py:362
#, python-format
msgid "instance %(nm)s: injecting file to %(plain_path)s"
msgstr "实例%(nm)s:正在注入文件到%(plain_path)s"

#: ../nova/compute/manager.py:902
#, python-format
msgid "instance %s: rescuing"
msgstr "实例%s：救援中..."

#: ../nova/compute/manager.py:924
#, python-format
msgid "instance %s: unrescuing"
msgstr "实例%s:取消救援"

#: ../nova/compute/manager.py:1191
#, python-format
msgid "instance %s: pausing"
msgstr "实例 %s: 暂停"

#: ../nova/compute/manager.py:1208
#, python-format
msgid "instance %s: unpausing"
msgstr "实例 %s: 取消暫停"

#: ../nova/compute/manager.py:1236
#, python-format
msgid "instance %s: retrieving diagnostics"
msgstr "实例 %s: 取消检测"

#: ../nova/compute/manager.py:1244
#, python-format
msgid "instance %s: suspending"
msgstr "虚拟机 %s：挂起"

#: ../nova/compute/manager.py:1261
#, python-format
msgid "instance %s: resuming"
msgstr "实例 %s: 唤醒中。。。"

#: ../nova/compute/manager.py:1279
#, python-format
msgid "instance %s: locking"
msgstr "实例%s:锁定中"

#: ../nova/compute/manager.py:1287
#, python-format
msgid "instance %s: unlocking"
msgstr "实例%s:取消锁定"

#: ../nova/compute/manager.py:1294
#, python-format
msgid "instance %s: getting locked state"
msgstr "实例%s：获取锁状态"

#: ../nova/compute/manager.py:1303
#, python-format
msgid "instance %s: reset network"
msgstr "实例%s:重置网络"

#: ../nova/compute/manager.py:1323 ../nova/api/ec2/cloud.py:800
#, python-format
msgid "Get console output for instance %s"
msgstr "获取虚拟机 %s 控制台输出"

#: ../nova/compute/manager.py:1332
#, python-format
msgid "instance %s: getting ajax console"
msgstr "虚拟机　%s ：获取ajax控制台"

#: ../nova/compute/manager.py:1239
#, python-format
msgid ""
"instance %(instance_id)s: attaching volume %(volume_id)s to %(mountpoint)s"
msgstr "实例%(instance_id)s:尝试挂载卷%(volume_id)s到%(mountpoint)s"

#. pylint: disable=W0702
#. NOTE(vish): The inline callback eats the exception info so we
#. log the traceback here and reraise the same
#. ecxception below.
#: ../nova/compute/manager.py:1265
#, python-format
msgid "instance %(instance_id)s: attach failed %(mountpoint)s, removing"
msgstr "实例%(instance_id)s：挂载到%(mountpoint)s失败，移除中"

#: ../nova/compute/manager.py:1423
#, python-format
msgid ""
"Detach volume %(volume_id)s from mountpoint %(mp)s on instance "
"%(instance_id)s"
msgstr "移除挂载在实例%(instance_id)s上的%(mp)s卷%(volume_id)s"

#: ../nova/compute/manager.py:1428
#, python-format
msgid "Detaching volume from unknown instance %s"
msgstr "从未知实例%s中移除卷"

#: ../nova/scheduler/simple.py:52
#, python-format
msgid "Host %s is not alive"
msgstr "服务器%s已关机"

#: ../nova/scheduler/simple.py:65
msgid "All hosts have too many cores"
msgstr "所有服务器拥有太多处理器"

#: ../nova/scheduler/simple.py:94 ../nova/scheduler/vsa.py:223
#, python-format
msgid "Host %s not available"
msgstr "连接不到服务器%s"

#: ../nova/scheduler/simple.py:117
msgid "All hosts have too many gigabytes"
msgstr "所有服务器拥有太多硬盘空间"

#: ../nova/scheduler/simple.py:134
msgid "All hosts have too many networks"
msgstr "所有服务器拥有太多网络"

#: ../nova/volume/manager.py:89
#, python-format
msgid "Re-exporting %s volumes"
msgstr "重新输出卷%s"

#: ../nova/volume/manager.py:94
#, python-format
msgid "volume %s: skipping export"
msgstr "跳过卷：%s"

#: ../nova/volume/manager.py:100
#, python-format
msgid "volume %s: creating"
msgstr "儲存量 %s: 在创造"

#: ../nova/volume/manager.py:112
#, python-format
msgid "volume %(vol_name)s: creating lv of size %(vol_size)sG"
msgstr "卷%(vol_name)s:创建大小为%(vol_size)s的逻辑卷"

#: ../nova/volume/manager.py:124
#, python-format
msgid "volume %s: creating export"
msgstr "卷%s：正在创建"

#: ../nova/volume/manager.py:138
#, python-format
msgid "volume %s: created successfully"
msgstr "卷%s：创建成功"

#: ../nova/volume/manager.py:167
msgid "Volume is still attached"
msgstr "卷仍在挂载中"

#: ../nova/volume/manager.py:169
msgid "Volume is not local to this node"
msgstr "卷不属于这个节点"

#: ../nova/volume/manager.py:173
#, python-format
msgid "volume %s: removing export"
msgstr "卷%s：移除中"

#: ../nova/volume/manager.py:175
#, python-format
msgid "volume %s: deleting"
msgstr "卷%s：删除中"

#: ../nova/volume/manager.py:190
#, python-format
msgid "volume %s: deleted successfully"
msgstr "卷%s：删除成功"

#: ../nova/virt/xenapi/fake.py:77 ../nova/virt/vmwareapi/fake.py:45
#, python-format
msgid "%(text)s: _db_content => %(content)s"
msgstr ""

#: ../nova/virt/xenapi/fake.py:492 ../nova/virt/xenapi/fake.py:591
#: ../nova/virt/xenapi/fake.py:609 ../nova/virt/xenapi/fake.py:672
msgid "Raising NotImplemented"
msgstr ""

#: ../nova/virt/xenapi/fake.py:494
#, python-format
msgid "xenapi.fake does not have an implementation for %s"
msgstr ""

#: ../nova/virt/xenapi/fake.py:528
#, python-format
msgid "Calling %(localname)s %(impl)s"
msgstr ""

#: ../nova/virt/xenapi/fake.py:533
#, python-format
msgid "Calling getter %s"
msgstr ""

#: ../nova/virt/xenapi/fake.py:593
#, python-format
msgid ""
"xenapi.fake does not have an implementation for %s or it has been called "
"with the wrong number of arguments"
msgstr ""

#: ../nova/tests/test_cloud.py:256
msgid "Can't test instances without a real virtual env."
msgstr ""

#: ../nova/tests/test_cloud.py:268
#, python-format
msgid "Need to watch instance %s until it's running..."
msgstr ""

#: ../nova/virt/connection.py:78
msgid "Failed to open connection to the hypervisor"
msgstr ""

#: ../nova/network/linux_net.py:923
#, python-format
msgid "Starting VLAN inteface %s"
msgstr ""

#: ../nova/network/linux_net.py:952
#, python-format
msgid "Starting Bridge interface for %s"
msgstr ""

#. pylint: disable=W0703
#: ../nova/network/linux_net.py:652
#, python-format
msgid "Hupping dnsmasq threw %s"
msgstr ""

#: ../nova/network/linux_net.py:654
#, python-format
msgid "Pid %d is stale, relaunching dnsmasq"
msgstr ""

#. pylint: disable=W0703
#: ../nova/network/linux_net.py:714
#, python-format
msgid "killing radvd threw %s"
msgstr ""

#: ../nova/network/linux_net.py:716
#, python-format
msgid "Pid %d is stale, relaunching radvd"
msgstr ""

#. pylint: disable=W0703
#: ../nova/network/linux_net.py:763
#, python-format
msgid "Killing dnsmasq threw %s"
msgstr ""

#: ../nova/utils.py:67
#, python-format
msgid "Inner Exception: %s"
msgstr "内层异常：%s"

#: ../nova/utils.py:59
#, python-format
msgid "Class %s cannot be found"
msgstr "无法找到 %s 类"

#: ../nova/utils.py:128
#, python-format
msgid "Fetching %s"
msgstr "正在抓取 %s"

#: ../nova/utils.py:169
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr "正在运行（在子进程中）运行命令：%s"

#: ../nova/utils.py:185 ../nova/utils.py:235
#, python-format
msgid "Result was %s"
msgstr "运行结果为 %s"

#: ../nova/utils.py:211
#, python-format
msgid "Running cmd (SSH): %s"
msgstr ""

#: ../nova/utils.py:275
#, python-format
msgid "debug in callback: %s"
msgstr "回调中debug：%s"

#: ../nova/utils.py:280
#, python-format
msgid "Running %s"
msgstr "正在运行 %s"

#: ../nova/utils.py:385
#, python-format
msgid "Link Local address is not found.:%s"
msgstr ""

#: ../nova/utils.py:388
#, python-format
msgid "Couldn't get Link Local IP of %(interface)s :%(ex)s"
msgstr ""

#: ../nova/utils.py:485
#, python-format
msgid "Invalid backend: %s"
msgstr "无效的后台：%s"

#: ../nova/utils.py:496
#, python-format
msgid "backend %s"
msgstr "后台 %s"

#: ../nova/fakerabbit.py:50
#, python-format
msgid "(%(nm)s) publish (key: %(routing_key)s) %(message)s"
msgstr ""

#: ../nova/fakerabbit.py:54
#, python-format
msgid "Publishing to route %s"
msgstr "发布并路由到 %s"

#: ../nova/fakerabbit.py:84
#, python-format
msgid "Declaring queue %s"
msgstr "正在声明队列 %s"

#: ../nova/fakerabbit.py:90
#, python-format
msgid "Declaring exchange %s"
msgstr "正在声明交换(exchange) %s"

#: ../nova/fakerabbit.py:96
#, python-format
msgid "Binding %(queue)s to %(exchange)s with key %(routing_key)s"
msgstr ""

#: ../nova/fakerabbit.py:133
#, python-format
msgid "Getting from %(queue)s: %(message)s"
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:192 ../nova/virt/hyperv.py:189
#, python-format
msgid "Created VM %s..."
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:195
#, python-format
msgid "Created VM %(instance_name)s as %(vm_ref)s."
msgstr ""

#: ../nova/virt/xenapi/volume_utils.py:208
#, python-format
msgid "Creating VBD for VM %(vm_ref)s, VDI %(vdi_ref)s ... "
msgstr ""

#: ../nova/virt/xenapi/volume_utils.py:211
#, python-format
msgid "Created VBD %(vbd_ref)s for VM %(vm_ref)s, VDI %(vdi_ref)s."
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:246
#, python-format
msgid "VBD not found in instance %s"
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:257
#, python-format
msgid "Unable to unplug VBD %s"
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:268
#, python-format
msgid "Unable to destroy VBD %s"
msgstr ""

#: ../nova/virt/xenapi/vmops.py:1383
#, python-format
msgid "Creating VIF for VM %(vm_ref)s, network %(network_ref)s."
msgstr ""

#: ../nova/virt/xenapi/vmops.py:1386
#, python-format
msgid "Created VIF %(vif_ref)s for VM %(vm_ref)s, network %(network_ref)s."
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:295
#, python-format
msgid ""
"Created VDI %(vdi_ref)s (%(name_label)s, %(virtual_size)s, %(read_only)s) on "
"%(sr_ref)s."
msgstr ""

#. TODO(sirp): Add quiesce and VSS locking support when Windows support
#. is added
#: ../nova/virt/xenapi/vm_utils.py:324
#, python-format
msgid "Snapshotting VM %(vm_ref)s with label '%(label)s'..."
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:338
#, python-format
msgid "Created snapshot %(template_vm_ref)s from VM %(vm_ref)s."
msgstr ""

#. NOTE(sirp): Currently we only support uploading images as VHD, there
#. is no RAW equivalent (yet)
#: ../nova/virt/xenapi/vm_utils.py:368
#, python-format
msgid "Asking xapi to upload %(vdi_uuids)s as ID %(image_id)s"
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:327
#, python-format
msgid "Size for image %(image)s:%(virtual_size)d"
msgstr ""

#. TODO(sirp): This should eventually be the URI for the Glance image
#: ../nova/virt/xenapi/vm_utils.py:1157
#, python-format
msgid "Glance image %s"
msgstr ""

#. We need to invoke a plugin for copying the
#. content of the VDI into the proper path.
#: ../nova/virt/xenapi/vm_utils.py:692
#, python-format
msgid "Copying VDI %s to /boot/guest on dom0"
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:702
#, python-format
msgid "Kernel/Ramdisk VDI %s destroyed"
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:361
#, python-format
msgid "Asking xapi to fetch %(url)s as %(access)s"
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:780
#, python-format
msgid "Looking up vdi %s for PV kernel"
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:397
#, python-format
msgid "PV Kernel in VDI:%s"
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:1307
#, python-format
msgid "Running pygrub against %s"
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:1314
#, python-format
msgid "Found Xen kernel %s"
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:1316
msgid "No Xen kernel found.  Booting HVM."
msgstr ""

#: ../nova/virt/hyperv.py:450
#, python-format
msgid "duplicate name found: %s"
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:832
#, python-format
msgid "VDI %s is still available"
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:870
#, python-format
msgid "(VM_UTILS) xenserver vm state -> |%s|"
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:872
#, python-format
msgid "(VM_UTILS) xenapi power_state -> |%s|"
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:1046
#, python-format
msgid "VHD %(vdi_uuid)s has parent %(parent_ref)s"
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:928
#, python-format
msgid "Re-scanning SR %s"
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:1097
#, python-format
msgid ""
"VHD coalesce attempts exceeded (%(counter)d > %(max_attempts)d), giving up..."
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:1104
#, python-format
msgid ""
"Parent %(parent_uuid)s doesn't match original parent "
"%(original_parent_uuid)s, waiting for coalesce..."
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:911
#, python-format
msgid "No VDIs found for VM %s"
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:594
#, python-format
msgid "Unexpected number of VDIs (%(num_vdis)s) found for VM %(vm_ref)s"
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:1234
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:188
#, python-format
msgid "Creating VBD for VDI %s ... "
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:1236
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:190
#, python-format
msgid "Creating VBD for VDI %s done."
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:1238
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:192
#, python-format
msgid "Plugging VBD %s ... "
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:1241
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:194
#, python-format
msgid "Plugging VBD %s done."
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:661
#, python-format
msgid "VBD %(vbd)s plugged as %(orig_dev)s"
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:664
#, python-format
msgid "VBD %(vbd)s plugged into wrong dev, remapping to %(dev)s"
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:1255
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:197
#, python-format
msgid "Destroying VBD for VDI %s ... "
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:1259
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:200
#, python-format
msgid "Destroying VBD for VDI %s done."
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:1271
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:211
msgid "VBD.unplug successful first time."
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:1276
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:216
msgid "VBD.unplug rejected: retrying..."
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:1281
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:220
msgid "VBD.unplug successful eventually."
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:1284
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:223
#, python-format
msgid "Ignoring XenAPI.Failure in VBD.unplug: %s"
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:1293
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:66
#, python-format
msgid "Ignoring XenAPI.Failure %s"
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:1140
#, python-format
msgid ""
"Writing partition table %(primary_first)d %(primary_last)d to %(dest)s..."
msgstr ""

#: ../nova/virt/xenapi/vm_utils.py:1353
#, python-format
msgid "Writing partition table %s done."
msgstr ""

#: ../nova/tests/rpc/common.py:142
#, python-format
msgid "Nested received %(queue)s, %(value)s"
msgstr ""

#: ../nova/tests/rpc/common.py:150
#, python-format
msgid "Nested return %s"
msgstr ""

#: ../nova/tests/rpc/common.py:176 ../nova/tests/rpc/common.py:182
#, python-format
msgid "Received %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:50
msgid "Use of empty request context is deprecated"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:133
#, python-format
msgid "No service for id %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:251
#, python-format
msgid "No service for %(host)s, %(binary)s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:592
msgid "No fixed ips defined"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:608
#, python-format
msgid "No floating ip for address %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:629
#, python-format
msgid "No address for instance %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:961
#, python-format
msgid "no keypair for user %(user_id)s, name %(name)s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1076 ../nova/db/sqlalchemy/api.py:1156
#, python-format
msgid "No network for id %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1086
msgid "No networks defined"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1115
#, python-format
msgid "No network for bridge %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1129 ../nova/db/sqlalchemy/api.py:1142
#, python-format
msgid "No network for instance %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1277
#, python-format
msgid "Token %s does not exist"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1302
#, python-format
msgid "No quota for project_id %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1455 ../nova/db/sqlalchemy/api.py:1501
#: ../nova/api/ec2/__init__.py:323
#, python-format
msgid "Volume %s not found"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1514
#, python-format
msgid "No export device found for volume %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1527
#, python-format
msgid "No target id found for volume %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1572
#, python-format
msgid "No security group with id %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1589
#, python-format
msgid "No security group named %(group_name)s for project: %(project_id)s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1682
#, python-format
msgid "No secuity group rule with id %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1756
#, python-format
msgid "No user for id %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1772
#, python-format
msgid "No user for access key %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1834
#, python-format
msgid "No project with id %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1979
#, python-format
msgid "No console pool with id %(pool_id)s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:1996
#, python-format
msgid ""
"No console pool of type %(console_type)s for compute host %(compute_host)s "
"on proxy host %(host)s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:2035
#, python-format
msgid "No console for instance %(instance_id)s in pool %(pool_id)s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:2057
#, python-format
msgid "on instance %s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:2058
#, python-format
msgid "No console with id %(console_id)s %(idesc)s"
msgstr ""

#: ../nova/db/sqlalchemy/api.py:2078 ../nova/db/sqlalchemy/api.py:2097
#, python-format
msgid "No zone with id %(zone_id)s"
msgstr ""

#: ../nova/compute/manager.py:192
#, python-format
msgid "Checking state of %s"
msgstr ""

#: ../nova/virt/libvirt_conn.py:165
#, python-format
msgid "Current state of %(name)s was %(state)s."
msgstr ""

#: ../nova/virt/libvirt/connection.py:226
#, python-format
msgid "Connecting to libvirt: %s"
msgstr ""

#: ../nova/virt/libvirt/connection.py:240
msgid "Connection to libvirt broke"
msgstr ""

#: ../nova/virt/libvirt/connection.py:390
#, python-format
msgid "instance %(instance_name)s: deleting instance files %(target)s"
msgstr ""

#: ../nova/virt/libvirt_conn.py:283
#, python-format
msgid "Invalid device path %s"
msgstr ""

#: ../nova/virt/libvirt_conn.py:313
#, python-format
msgid "No disk at %s"
msgstr ""

#: ../nova/virt/libvirt_conn.py:320
msgid "Instance snapshotting is not supported for libvirtat this time"
msgstr ""

#: ../nova/virt/libvirt_conn.py:336
#, python-format
msgid "instance %s: rebooted"
msgstr ""

#: ../nova/virt/libvirt_conn.py:339
#, python-format
msgid "_wait_for_reboot failed: %s"
msgstr ""

#: ../nova/virt/libvirt_conn.py:382
#, python-format
msgid "instance %s: rescued"
msgstr ""

#: ../nova/virt/libvirt_conn.py:385
#, python-format
msgid "_wait_for_rescue failed: %s"
msgstr ""

#: ../nova/virt/libvirt/connection.py:665
#, python-format
msgid "instance %s: is running"
msgstr ""

#: ../nova/virt/libvirt_conn.py:422
#, python-format
msgid "instance %s: booted"
msgstr ""

#: ../nova/virt/libvirt_conn.py:425 ../nova/virt/xenapi/vmops.py:186
#, python-format
msgid "instance %s: failed to boot"
msgstr ""

#: ../nova/virt/libvirt/connection.py:688
#, python-format
msgid "virsh said: %r"
msgstr ""

#: ../nova/virt/libvirt/connection.py:692
msgid "cool, it's a device"
msgstr ""

#: ../nova/virt/libvirt/connection.py:703
#, python-format
msgid "data: %(data)r, fpath: %(fpath)r"
msgstr ""

#: ../nova/virt/libvirt/connection.py:745
#, python-format
msgid "Contents of file %(fpath)s: %(contents)r"
msgstr ""

#: ../nova/virt/libvirt/utils.py:218
msgid "Unable to find an open port"
msgstr ""

#: ../nova/virt/libvirt/connection.py:849
#, python-format
msgid "instance %s: Creating image"
msgstr ""

#: ../nova/virt/libvirt_conn.py:646
#, python-format
msgid "instance %(inst_name)s: injecting key into image %(img_id)s"
msgstr ""

#: ../nova/virt/libvirt_conn.py:649
#, python-format
msgid "instance %(inst_name)s: injecting net into image %(img_id)s"
msgstr ""

#. This could be a windows image, or a vmdk format disk
#: ../nova/virt/libvirt/connection.py:1039
#, python-format
msgid ""
"instance %(inst_name)s: ignoring error injecting data into image %(img_id)s "
"(%(e)s)"
msgstr ""

#. TODO(termie): cache?
#: ../nova/virt/libvirt/connection.py:1178
#, python-format
msgid "instance %s: starting toXML method"
msgstr ""

#: ../nova/virt/libvirt/connection.py:1182
#, python-format
msgid "instance %s: finished toXML method"
msgstr ""

#: ../nova/virt/libvirt/connection.py:1330
msgid "diagnostics are not supported for libvirt"
msgstr ""

#: ../nova/virt/libvirt/firewall.py:540
#, python-format
msgid "Attempted to unfilter instance %s which is not filtered"
msgstr ""

#: ../nova/api/metadata/handler.py:250 ../nova/api/metadata/handler.py:257
#, python-format
msgid "Failed to get metadata for ip: %s"
msgstr ""

#: ../nova/auth/fakeldap.py:33
msgid "Attempted to instantiate singleton"
msgstr ""

#: ../nova/network/api.py:39
#, python-format
msgid "Quota exceeeded for %s, tried to allocate address"
msgstr ""

#: ../nova/network/manager.py:296
msgid "Address quota exceeded. You cannot allocate any more addresses"
msgstr ""

#: ../nova/tests/test_volume.py:190
#, python-format
msgid "Target %s allocated"
msgstr ""

#: ../nova/virt/images.py:70
#, python-format
msgid "Finished retreving %(url)s -- placed in %(path)s"
msgstr ""

#: ../nova/scheduler/driver.py:165
msgid "Must implement a fallback schedule"
msgstr ""

#: ../nova/console/manager.py:71 ../nova/console/vmrc_manager.py:64
msgid "Adding console"
msgstr ""

#: ../nova/console/manager.py:91
#, python-format
msgid "Tried to remove non-existant console %(console_id)s."
msgstr ""

#: ../nova/api/direct.py:219
msgid "not available"
msgstr ""

#: ../nova/api/ec2/cloud.py:62
#, python-format
msgid "The key_pair %s already exists"
msgstr ""

#. TODO(vish): Do this with M2Crypto instead
#: ../nova/api/ec2/cloud.py:227
#, python-format
msgid "Generating root CA: %s"
msgstr "生成根证书: %s"

#: ../nova/api/ec2/cloud.py:385
#, python-format
msgid "Create key pair %s"
msgstr "创建键值对 %s"

#: ../nova/api/ec2/cloud.py:414
#, python-format
msgid "Delete key pair %s"
msgstr "删除键值对 %s"

#: ../nova/api/ec2/cloud.py:386
#, python-format
msgid "%s is not a valid ipProtocol"
msgstr "%s 是无效的IP协议"

#: ../nova/api/ec2/cloud.py:390
msgid "Invalid port range"
msgstr "端口范围无效"

#: ../nova/api/openstack/v2/contrib/security_groups.py:348
#, python-format
msgid "Revoke security group ingress %s"
msgstr "撤销输入安全组 %s"

#: ../nova/api/openstack/v2/contrib/security_groups.py:210
msgid "Not enough parameters to build a valid rule."
msgstr ""

#: ../nova/api/ec2/cloud.py:673 ../nova/api/ec2/cloud.py:729
msgid "No rule for the specified parameters."
msgstr "对给定的参数无特定规则。"

#: ../nova/api/openstack/v2/contrib/security_groups.py:195
#, python-format
msgid "Authorize security group ingress %s"
msgstr "验证输入安全组 %s"

#: ../nova/api/openstack/v2/contrib/security_groups.py:217
#, python-format
msgid "This rule already exists in group %s"
msgstr "这条规则已经存在安全组 %s 中。"

#: ../nova/api/ec2/cloud.py:765
#: ../nova/api/openstack/v2/contrib/security_groups.py:137
#, python-format
msgid "Create Security Group %s"
msgstr "创建安全组 %s"

#: ../nova/api/ec2/cloud.py:768
#, python-format
msgid "group %s already exists"
msgstr "安全组 %s 已经存在"

#: ../nova/api/ec2/cloud.py:795
#: ../nova/api/openstack/v2/contrib/security_groups.py:97
#, python-format
msgid "Delete security group %s"
msgstr "删除安全组 %s"

#: ../nova/api/openstack/v2/contrib/volumes.py:157
#: ../nova/api/ec2/cloud.py:887
#, python-format
msgid "Create volume of %s GB"
msgstr ""

#: ../nova/api/ec2/cloud.py:922
#, python-format
msgid "Attach volume %(volume_id)s to instance %(instance_id)s at %(device)s"
msgstr ""

#: ../nova/api/openstack/v2/contrib/volumes.py:302
#: ../nova/api/ec2/cloud.py:936
#, python-format
msgid "Detach volume %s"
msgstr ""

#: ../nova/api/ec2/cloud.py:1221
msgid "Allocate address"
msgstr ""

#: ../nova/api/ec2/cloud.py:1233
#, python-format
msgid "Release address %s"
msgstr ""

#: ../nova/api/ec2/cloud.py:1238
#, python-format
msgid "Associate address %(public_ip)s to instance %(instance_id)s"
msgstr ""

#: ../nova/api/ec2/cloud.py:1247
#, python-format
msgid "Disassociate address %s"
msgstr ""

#: ../nova/api/ec2/cloud.py:1303
msgid "Going to start terminating instances"
msgstr ""

#: ../nova/api/ec2/cloud.py:1312
#, python-format
msgid "Reboot instance %r"
msgstr ""

#: ../nova/api/ec2/cloud.py:1446
#, python-format
msgid "De-registering image %s"
msgstr ""

#: ../nova/api/ec2/cloud.py:1473
#, python-format
msgid "Registered image %(image_location)s with id %(image_id)s"
msgstr ""

#: ../nova/api/ec2/cloud.py:963 ../nova/api/ec2/cloud.py:1024
#: ../nova/api/ec2/cloud.py:1501 ../nova/api/ec2/cloud.py:1516
#, python-format
msgid "attribute not supported: %s"
msgstr ""

#: ../nova/api/ec2/cloud.py:890
#, python-format
msgid "invalid id: %s"
msgstr ""

#: ../nova/api/ec2/cloud.py:1519
msgid "user or group not specified"
msgstr ""

#: ../nova/api/ec2/cloud.py:1521
msgid "only group \"all\" is supported"
msgstr ""

#: ../nova/api/ec2/cloud.py:1523
msgid "operation_type must be add or remove"
msgstr ""

#: ../nova/api/ec2/cloud.py:1524
#, python-format
msgid "Updating image %s publicity"
msgstr ""

#: ../bin/nova-api.py:52
#, python-format
msgid "Using paste.deploy config at: %s"
msgstr ""

#: ../bin/nova-api.py:57
#, python-format
msgid "No paste configuration for app: %s"
msgstr ""

#: ../bin/nova-api.py:59
#, python-format
msgid ""
"App Config: %(api)s\n"
"%(config)r"
msgstr ""

#: ../bin/nova-api.py:64
#, python-format
msgid "Running %s API"
msgstr ""

#: ../bin/nova-api.py:69
#, python-format
msgid "No known API applications configured in %s."
msgstr ""

#: ../bin/nova-api.py:83
#, python-format
msgid "Starting nova-api node (version %s)"
msgstr ""

#: ../bin/nova-api.py:89
#, python-format
msgid "No paste configuration found for: %s"
msgstr ""

#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:84
#, python-format
msgid "Argument %(key)s value %(value)s is too short."
msgstr ""

#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:89
#, python-format
msgid "Argument %(key)s value %(value)s contains invalid characters."
msgstr ""

#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:94
#, python-format
msgid "Argument %(key)s value %(value)s starts with a hyphen."
msgstr ""

#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:102
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:130
#, python-format
msgid "Argument %s is required."
msgstr ""

#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:117
#, python-format
msgid ""
"Argument %(key)s may not take value %(value)s. Valid values are ['true', "
"'false']."
msgstr ""

#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py:163
#, python-format
msgid ""
"Created VDI %(vdi_ref)s (%(label)s, %(size)s, %(read_only)s) on %(sr_ref)s."
msgstr ""

#: ../nova/virt/xenapi/vmops.py:67
#, python-format
msgid "Attempted to create non-unique name %s"
msgstr ""

#: ../nova/virt/xenapi/vmops.py:73
#, python-format
msgid "instance %(name)s: not enough free memory"
msgstr ""

#: ../nova/virt/xenapi/vmops.py:383
#, python-format
msgid "Starting VM %s..."
msgstr ""

#: ../nova/virt/xenapi/vmops.py:386
#, python-format
msgid "Spawning VM %(instance_name)s created %(vm_ref)s."
msgstr ""

#: ../nova/virt/xenapi/vmops.py:162
#, python-format
msgid "Invalid value for onset_files: '%s'"
msgstr ""

#: ../nova/virt/xenapi/vmops.py:432
#, python-format
msgid "Injecting file path: '%s'"
msgstr ""

#: ../nova/virt/xenapi/vmops.py:462
#, python-format
msgid "Instance %s: booted"
msgstr ""

#: ../nova/virt/xenapi/vmops.py:232
#, python-format
msgid "Instance not present %s"
msgstr ""

#. TODO(sirp): Add quiesce and VSS locking support when Windows support
#. is added
#: ../nova/virt/xenapi/vmops.py:607
#, python-format
msgid "Starting snapshot for VM %s"
msgstr ""

#: ../nova/virt/xenapi/vmops.py:616
#, python-format
msgid "Unable to Snapshot %(vm_ref)s: %(exc)s"
msgstr ""

#: ../nova/virt/xenapi/vmops.py:601
#, python-format
msgid "Finished snapshot and upload for VM %s"
msgstr ""

#: ../nova/virt/xenapi/vmops.py:356
#, python-format
msgid "VM %(vm)s already halted, skipping shutdown..."
msgstr ""

#: ../nova/virt/xenapi/vmops.py:389
msgid "Removing kernel/ramdisk files"
msgstr ""

#: ../nova/virt/xenapi/vmops.py:1018
msgid "kernel/ramdisk files removed"
msgstr ""

#: ../nova/virt/xenapi/vmops.py:561
#, python-format
msgid ""
"TIMEOUT: The call to %(method)s timed out. VM id=%(instance_id)s; "
"args=%(strargs)s"
msgstr ""

#: ../nova/virt/xenapi/vmops.py:564
#, python-format
msgid ""
"NOT IMPLEMENTED: The call to %(method)s is not supported by the agent. VM "
"id=%(instance_id)s; args=%(strargs)s"
msgstr ""

#: ../nova/virt/xenapi/vmops.py:569
#, python-format
msgid ""
"The call to %(method)s returned an error: %(e)s. VM id=%(instance_id)s; "
"args=%(strargs)s"
msgstr ""

#: ../nova/virt/xenapi/vmops.py:1693
#, python-format
msgid "OpenSSL error: %s"
msgstr ""

#: ../nova/tests/test_compute.py:204 ../nova/tests/test_compute.py:1026
#, python-format
msgid "Running instances: %s"
msgstr ""

#: ../nova/tests/test_compute.py:210
#, python-format
msgid "After terminating instances: %s"
msgstr ""

#: ../nova/cloudpipe/pipelib.py:45
msgid "Template for script to run on cloudpipe instance boot"
msgstr ""

#: ../nova/cloudpipe/pipelib.py:48
msgid "Network to push into openvpn config"
msgstr ""

#: ../nova/cloudpipe/pipelib.py:51
msgid "Netmask to push into openvpn config"
msgstr ""

#: ../nova/cloudpipe/pipelib.py:96
#, python-format
msgid "Launching VPN for %s"
msgstr ""

#: ../nova/db/sqlalchemy/migration.py:36
msgid "python-migrate is not installed. Exiting."
msgstr ""

#: ../nova/image/s3.py:99
#, python-format
msgid "Image %s could not be found"
msgstr ""

#: ../nova/api/ec2/__init__.py:134
msgid "Too many failed authentications."
msgstr "认证失败过多"

#: ../nova/api/ec2/__init__.py:144
#, python-format
msgid ""
"Access key %(access_key)s has had %(failures)d failed authentications and "
"will be locked out for %(lock_mins)d minutes."
msgstr ""

#: ../nova/api/ec2/__init__.py:204
#, python-format
msgid "Authentication Failure: %s"
msgstr "认证失败：%s"

#: ../nova/api/ec2/__init__.py:220
#, python-format
msgid "Authenticated Request For %(uname)s:%(pname)s)"
msgstr ""

#: ../nova/api/ec2/__init__.py:251
#, python-format
msgid "action: %s"
msgstr "执行: %s"

#: ../nova/api/ec2/__init__.py:253
#, python-format
msgid "arg: %(key)s\t\tval: %(value)s"
msgstr ""

#: ../nova/api/ec2/__init__.py:328
#, python-format
msgid ""
"Unauthorized request for controller=%(controller)s and action=%(action)s"
msgstr ""

#: ../nova/api/ec2/__init__.py:359
#, python-format
msgid "InstanceNotFound raised: %s"
msgstr ""

#: ../nova/api/ec2/__init__.py:365
#, python-format
msgid "VolumeNotFound raised: %s"
msgstr ""

#: ../nova/api/ec2/__init__.py:377
#, python-format
msgid "NotFound raised: %s"
msgstr "引起没有找到的错误: %s"

#: ../nova/api/ec2/__init__.py:380
#, python-format
msgid "ApiError raised: %s"
msgstr "引发了Api错误: %s"

#: ../nova/api/ec2/__init__.py:409
#, python-format
msgid "Unexpected error raised: %s"
msgstr "引发了意外的错误：%s"

#: ../nova/api/metadata/handler.py:252 ../nova/api/ec2/__init__.py:414
msgid "An unknown error has occurred. Please try your request again."
msgstr "发生了一个未知的错误. 请重试你的请求."

#: ../nova/auth/dbdriver.py:84
#, python-format
msgid "User %s already exists"
msgstr ""

#: ../nova/auth/dbdriver.py:106 ../nova/auth/ldapdriver.py:232
#, python-format
msgid "Project can't be created because manager %s doesn't exist"
msgstr ""

#: ../nova/auth/dbdriver.py:122 ../nova/auth/ldapdriver.py:243
#, python-format
msgid "Project can't be created because user %s doesn't exist"
msgstr ""

#: ../nova/auth/dbdriver.py:135 ../nova/auth/ldapdriver.py:229
#, python-format
msgid "Project can't be created because project %s already exists"
msgstr ""

#: ../nova/auth/dbdriver.py:157 ../nova/auth/ldapdriver.py:268
#, python-format
msgid "Project can't be modified because manager %s doesn't exist"
msgstr ""

#: ../nova/auth/dbdriver.py:245
#, python-format
msgid "User \"%s\" not found"
msgstr ""

#: ../nova/auth/dbdriver.py:248
#, python-format
msgid "Project \"%s\" not found"
msgstr ""

#: ../nova/virt/xenapi_conn.py:159
msgid ""
"Must specify xenapi_connection_url, xenapi_connection_username (optionally), "
"and xenapi_connection_password to use connection_type=xenapi"
msgstr ""

#: ../nova/virt/xenapi_conn.py:534
#, python-format
msgid "Task [%(name)s] %(task)s status: success    %(result)s"
msgstr ""

#: ../nova/virt/xenapi_conn.py:543
#, python-format
msgid "Task [%(name)s] %(task)s status: %(status)s    %(error_info)s"
msgstr ""

#: ../nova/virt/xenapi_conn.py:569 ../nova/virt/xenapi_conn.py:582
#, python-format
msgid "Got exception: %s"
msgstr ""

#: ../nova/volume/driver.py:352
#, python-format
msgid "Could not find iSCSI export  for volume %s"
msgstr ""

#: ../nova/api/ec2/apirequest.py:73
#, python-format
msgid ""
"Unsupported API request: controller = %(controller)s, action = %(action)s"
msgstr ""

#: ../nova/api/openstack/v2/__init__.py:63
#, python-format
msgid "Caught error: %s"
msgstr ""

#: ../nova/api/openstack/v2/__init__.py:113
msgid "Including admin operations in API."
msgstr ""

#: ../nova/console/xvp.py:93
msgid "Rebuilding xvp conf"
msgstr ""

#: ../nova/console/xvp.py:111
#, python-format
msgid "Re-wrote %s"
msgstr ""

#: ../nova/console/xvp.py:116
msgid "Stopping xvp"
msgstr ""

#: ../nova/console/xvp.py:129
msgid "Starting xvp"
msgstr ""

#: ../nova/console/xvp.py:136
#, python-format
msgid "Error starting xvp: %s"
msgstr ""

#: ../nova/console/xvp.py:139
msgid "Restarting xvp"
msgstr ""

#: ../nova/console/xvp.py:141
msgid "xvp not running..."
msgstr ""

#: ../bin/nova-manage.py:272
msgid ""
"The above error may show that the database has not been created.\n"
"Please create a database using nova-manage sync db before running this "
"command."
msgstr ""

#: ../bin/nova-manage.py:426
msgid ""
"No more networks available. If this is a new installation, you need\n"
"to call something like this:\n"
"\n"
"    nova-manage network create 10.0.0.0/8 10 64\n"
"\n"
msgstr ""

#: ../bin/nova-manage.py:609
msgid ""
"The above error may show that the certificate db has not been created.\n"
"Please create a database by running a nova-api server on this host."
msgstr ""

#: ../bin/nova-manage.py:633
msgid "network"
msgstr ""

#: ../bin/nova-manage.py:634
msgid "IP address"
msgstr ""

#: ../bin/nova-manage.py:635
msgid "MAC address"
msgstr ""

#: ../bin/nova-manage.py:636
msgid "hostname"
msgstr ""

#: ../bin/nova-manage.py:637 ../bin/nova-manage.py:1136
#: ../bin/nova-manage.py:1252 ../bin/nova-manage.py:1284
msgid "host"
msgstr ""

#: ../bin/nova-manage.py:537
msgid "netmask"
msgstr ""

#: ../bin/nova-manage.py:832 ../nova/tests/test_nova_manage.py:183
msgid "start address"
msgstr ""

#: ../nova/virt/disk.py:124
#, python-format
msgid "Failed to load partition: %s"
msgstr ""

#: ../nova/virt/disk.py:148 ../nova/virt/disk.py:180
#, python-format
msgid "Failed to mount filesystem: %s"
msgstr ""

#: ../nova/virt/disk.py:217
#, python-format
msgid "nbd device %s did not show up"
msgstr ""

#: ../nova/virt/disk.py:222
#, python-format
msgid "Could not attach image to loopback: %s"
msgstr ""

#: ../nova/virt/disk.py:246
msgid "No free nbd devices"
msgstr ""

#: ../doc/ext/nova_todo.py:46
#, python-format
msgid "%(filename)s, line %(line_info)d"
msgstr ""

#. FIXME(chiradeep): implement this
#: ../nova/virt/hyperv.py:119
msgid "In init host"
msgstr ""

#: ../nova/virt/hyperv.py:131
#, python-format
msgid "Attempt to create duplicate vm %s"
msgstr ""

#: ../nova/virt/hyperv.py:166
#, python-format
msgid "Starting VM %s "
msgstr ""

#: ../nova/virt/hyperv.py:168
#, python-format
msgid "Started VM %s "
msgstr ""

#: ../nova/virt/hyperv.py:170
#, python-format
msgid "spawn vm failed: %s"
msgstr ""

#: ../nova/virt/hyperv.py:187
#, python-format
msgid "Failed to create VM %s"
msgstr ""

#: ../nova/virt/hyperv.py:206
#, python-format
msgid "Set memory for vm %s..."
msgstr ""

#: ../nova/virt/hyperv.py:216
#, python-format
msgid "Set vcpus for vm %s..."
msgstr ""

#: ../nova/virt/hyperv.py:220
#, python-format
msgid "Creating disk for %(vm_name)s by attaching disk file %(vhdfile)s"
msgstr ""

#: ../nova/virt/hyperv.py:245
#, python-format
msgid "Failed to add diskdrive to VM %s"
msgstr ""

#: ../nova/virt/hyperv.py:248
#, python-format
msgid "New disk drive path is %s"
msgstr ""

#: ../nova/virt/hyperv.py:265
#, python-format
msgid "Failed to add vhd file to VM %s"
msgstr ""

#: ../nova/virt/hyperv.py:267
#, python-format
msgid "Created disk for %s"
msgstr ""

#: ../nova/virt/hyperv.py:271
#, python-format
msgid "Creating nic for %s "
msgstr ""

#: ../nova/virt/hyperv.py:290
msgid "Failed creating a port on the external vswitch"
msgstr ""

#: ../nova/virt/hyperv.py:291
#, python-format
msgid "Failed creating port for %s"
msgstr ""

#: ../nova/virt/hyperv.py:294
#, python-format
msgid "Created switch port %(vm_name)s on switch %(ext_path)s"
msgstr ""

#: ../nova/virt/hyperv.py:304
#, python-format
msgid "Failed to add nic to VM %s"
msgstr ""

#: ../nova/virt/hyperv.py:306
#, python-format
msgid "Created nic for %s "
msgstr ""

#: ../nova/virt/hyperv.py:339
#, python-format
msgid "WMI job failed: %s"
msgstr ""

#: ../nova/virt/hyperv.py:343
#, python-format
msgid "WMI job succeeded: %(desc)s, Elapsed=%(elap)s "
msgstr ""

#: ../nova/virt/hyperv.py:380
#, python-format
msgid "Got request to destroy vm %s"
msgstr ""

#: ../nova/virt/hyperv.py:405
#, python-format
msgid "Failed to destroy vm %s"
msgstr ""

#: ../nova/virt/hyperv.py:412
#, python-format
msgid "Del: disk %(vhdfile)s vm %(instance_name)s"
msgstr ""

#: ../nova/virt/hyperv.py:433
#, python-format
msgid ""
"Got Info for vm %(instance_id)s: state=%(state)s, mem=%(memusage)s, "
"num_cpu=%(numprocs)s, cpu_time=%(uptime)s"
msgstr ""

#: ../nova/virt/hyperv.py:470
#, python-format
msgid "Successfully changed vm state of %(vm_name)s to %(req_state)s"
msgstr ""

#: ../nova/virt/hyperv.py:473
#, python-format
msgid "Failed to change vm state of %(vm_name)s to %(req_state)s"
msgstr ""

#: ../nova/compute/api.py:71
#, python-format
msgid "Instance %d was not found in get_network_topic"
msgstr ""

#: ../nova/compute/api.py:77
#, python-format
msgid "Instance %d has no host"
msgstr ""

#: ../nova/compute/api.py:97
#, python-format
msgid "Quota exceeeded for %(pid)s, tried to run %(min_count)s instances"
msgstr ""

#: ../nova/compute/api.py:199
#, python-format
msgid ""
"Instance quota exceeded. You can only run %s more instances of this type."
msgstr ""

#: ../nova/compute/api.py:248
msgid "Creating a raw instance"
msgstr ""

#: ../nova/compute/api.py:303
#, python-format
msgid "Going to run %s instances..."
msgstr ""

#: ../nova/compute/api.py:187
#, python-format
msgid "Casting to scheduler for %(pid)s/%(uid)s's instance %(instance_id)s"
msgstr ""

#: ../nova/compute/api.py:814
#, python-format
msgid "Going to try to terminate %s"
msgstr ""

#: ../nova/compute/api.py:296
#, python-format
msgid "Instance %d was not found during terminate"
msgstr ""

#: ../nova/compute/api.py:301
#, python-format
msgid "Instance %d is already being terminated"
msgstr ""

#: ../nova/compute/api.py:1516
#, python-format
msgid "Invalid device specified: %s. Example device: /dev/vdb"
msgstr ""

#: ../nova/compute/api.py:1531
msgid "Volume isn't attached to anything!"
msgstr ""

#: ../nova/rpc.py:98
#, python-format
msgid ""
"AMQP server on %(fl_host)s:%(fl_port)d is unreachable. Trying again in "
"%(fl_intv)d seconds."
msgstr ""

#: ../nova/rpc.py:103
#, python-format
msgid "Unable to connect to AMQP server after %d tries. Shutting down."
msgstr "已尝试 %d 次，均无法连接到AMQP服务器。关闭中。"

#: ../nova/rpc/impl_carrot.py:220
msgid "Reconnected to queue"
msgstr "重新与队列建立连接"

#: ../nova/rpc.py:129
msgid "Failed to fetch message from queue"
msgstr "从队列获取数据失败"

#: ../nova/rpc/impl_carrot.py:235
#, python-format
msgid "Initing the Adapter Consumer for %s"
msgstr ""

#: ../nova/rpc/impl_kombu.py:600 ../nova/rpc/impl_carrot.py:255
#, python-format
msgid "received %s"
msgstr "已接收 %s"

#. NOTE(vish): we may not want to ack here, but that means that bad
#. messages stay in the queue indefinitely, so for now
#. we just log the message and send an error string
#. back to the caller
#: ../nova/rpc/impl_kombu.py:605 ../nova/rpc/impl_carrot.py:268
#, python-format
msgid "no method for message: %s"
msgstr "没有适用于消息 %s 的方法"

#: ../nova/rpc/impl_kombu.py:606 ../nova/rpc/impl_carrot.py:270
#, python-format
msgid "No method for message: %s"
msgstr "没有适用于消息 %s 的方法"

#: ../nova/rpc/impl_kombu.py:779 ../nova/rpc/impl_carrot.py:453
#, python-format
msgid "Returning exception %s to caller"
msgstr "返回 %s 异常给调用者"

#: ../nova/rpc/impl_kombu.py:646 ../nova/rpc/impl_carrot.py:486
#, python-format
msgid "unpacked context: %s"
msgstr ""

#: ../nova/rpc.py:313
msgid "Making asynchronous call..."
msgstr "产生异步调用中……"

#: ../nova/rpc/impl_kombu.py:733 ../nova/rpc/impl_carrot.py:522
#, python-format
msgid "MSG_ID is %s"
msgstr "消息ID(MSG_ID)是 %s"

#: ../nova/rpc.py:354
msgid "Making asynchronous cast..."
msgstr ""

#: ../nova/rpc/impl_carrot.py:621
#, python-format
msgid "response %s"
msgstr "回复 %s"

#: ../nova/rpc/impl_carrot.py:630
#, python-format
msgid "topic is %s"
msgstr "话题是 %s"

#: ../nova/rpc/impl_carrot.py:631
#, python-format
msgid "message %s"
msgstr "消息 %s"

#: ../nova/volume/driver.py:77
#, python-format
msgid "Recovering from a failed execute.  Try number %s"
msgstr ""

#: ../nova/volume/driver.py:87
#, python-format
msgid "volume group %s doesn't exist"
msgstr ""

#: ../nova/volume/driver.py:342
#, python-format
msgid "FAKE AOE: %s"
msgstr ""

#: ../nova/volume/driver.py:249 ../nova/volume/driver.py:832
msgid "Skipping ensure_export. No iscsi_target "
msgstr ""

#: ../nova/volume/driver.py:288 ../nova/volume/driver.py:297
#: ../nova/volume/driver.py:876
msgid "Skipping remove_export. No iscsi_target "
msgstr ""

#: ../nova/volume/driver.py:456
#, python-format
msgid "FAKE ISCSI: %s"
msgstr ""

#: ../nova/volume/driver.py:468
#, python-format
msgid "rbd has no pool %s"
msgstr ""

#: ../nova/volume/driver.py:535
#, python-format
msgid "Sheepdog is not working: %s"
msgstr ""

#: ../nova/volume/driver.py:537
msgid "Sheepdog is not working"
msgstr ""

#: ../nova/wsgi.py:68
#, python-format
msgid "Starting %(arg0)s on %(host)s:%(port)s"
msgstr ""

#: ../nova/wsgi.py:208
msgid "You must implement __call__"
msgstr ""

#: ../bin/nova-dhcpbridge.py:58
msgid "leasing ip"
msgstr ""

#: ../bin/nova-dhcpbridge.py:73
msgid "Adopted old lease or got a change of mac/hostname"
msgstr ""

#: ../bin/nova-dhcpbridge.py:78
msgid "releasing ip"
msgstr ""

#: ../bin/nova-dhcpbridge.py:123
#, python-format
msgid ""
"Called %(action)s for mac %(mac)s with ip %(ip)s and hostname %(hostname)s "
"on interface %(interface)s"
msgstr ""

#: ../nova/virt/fake.py:239
#, python-format
msgid "Instance %s Not Found"
msgstr ""

#: ../nova/network/manager.py:386
#, python-format
msgid "Dissassociated %s stale fixed ip(s)"
msgstr ""

#: ../nova/network/manager.py:524
msgid "setting network host"
msgstr ""

#: ../nova/network/manager.py:212
#, python-format
msgid "Leasing IP %s"
msgstr ""

#: ../nova/network/manager.py:216
#, python-format
msgid "IP %s leased that isn't associated"
msgstr ""

#: ../nova/network/manager.py:220
#, python-format
msgid "IP %(address)s leased to bad mac %(inst_addr)s vs %(mac)s"
msgstr ""

#: ../nova/network/manager.py:228
#, python-format
msgid "IP %s leased that was already deallocated"
msgstr ""

#: ../nova/network/manager.py:233
#, python-format
msgid "Releasing IP %s"
msgstr ""

#: ../nova/network/manager.py:237
#, python-format
msgid "IP %s released that isn't associated"
msgstr ""

#: ../nova/network/manager.py:241
#, python-format
msgid "IP %(address)s released from bad mac %(inst_addr)s vs %(mac)s"
msgstr ""

#: ../nova/network/manager.py:871
#, python-format
msgid "IP %s released that was not leased"
msgstr ""

#: ../nova/network/manager.py:1279
msgid ""
"The sum between the number of networks and the vlan start cannot be greater "
"than 4094"
msgstr ""

#: ../nova/virt/xenapi/volume_utils.py:159
#, python-format
msgid "Introducing %s..."
msgstr ""

#: ../nova/virt/xenapi/volume_utils.py:103
#: ../nova/virt/xenapi/volume_utils.py:172
#: ../nova/virt/xenapi/volumeops.py:157
#, python-format
msgid "Introduced %(label)s as %(sr_ref)s."
msgstr ""

#: ../nova/virt/xenapi/volume_utils.py:76
#: ../nova/virt/xenapi/volume_utils.py:176
msgid "Unable to create Storage Repository"
msgstr ""

#: ../nova/virt/xenapi/volume_utils.py:188
#, python-format
msgid "Unable to find SR from VBD %s"
msgstr ""

#: ../nova/virt/xenapi/volume_utils.py:96
#, python-format
msgid "Forgetting SR %s ... "
msgstr ""

#: ../nova/virt/xenapi/volume_utils.py:230
#, python-format
msgid "Ignoring exception %(exc)s when getting PBDs for %(sr_ref)s"
msgstr ""

#: ../nova/virt/xenapi/volume_utils.py:236
#, python-format
msgid "Ignoring exception %(exc)s when unplugging PBD %(pbd)s"
msgstr ""

#: ../nova/virt/xenapi/volume_utils.py:111
#, python-format
msgid "Forgetting SR %s done."
msgstr ""

#: ../nova/virt/xenapi/volume_utils.py:113
#, python-format
msgid "Ignoring exception %(exc)s when forgetting SR %(sr_ref)s"
msgstr ""

#: ../nova/virt/xenapi/volume_utils.py:251
#, python-format
msgid "Unable to introduce VDI on SR %s"
msgstr ""

#: ../nova/virt/xenapi/volume_utils.py:259
#, python-format
msgid "Unable to get record of VDI %s on"
msgstr ""

#: ../nova/virt/xenapi/volume_utils.py:281
#, python-format
msgid "Unable to introduce VDI for SR %s"
msgstr ""

#: ../nova/virt/xenapi/volume_utils.py:175
#, python-format
msgid "Unable to obtain target information %(device_path)s, %(mountpoint)s"
msgstr ""

#: ../nova/virt/xenapi/volume_utils.py:358
#, python-format
msgid "Mountpoint cannot be translated: %s"
msgstr ""

#: ../nova/image/s3.py:365
#, python-format
msgid "Failed to decrypt private key: %s"
msgstr ""

#: ../nova/image/s3.py:374
#, python-format
msgid "Failed to decrypt initialization vector: %s"
msgstr ""

#: ../nova/image/s3.py:385
#, python-format
msgid "Failed to decrypt image file %(image_file)s: %(err)s"
msgstr ""

#: ../nova/objectstore/handler.py:106
#, python-format
msgid "Unknown S3 value type %r"
msgstr ""

#: ../nova/objectstore/handler.py:137
msgid "Authenticated request"
msgstr ""

#: ../nova/objectstore/handler.py:182
msgid "List of buckets requested"
msgstr ""

#: ../nova/objectstore/handler.py:209
#, python-format
msgid "List keys for bucket %s"
msgstr ""

#: ../nova/objectstore/handler.py:217
#, python-format
msgid "Unauthorized attempt to access bucket %s"
msgstr ""

#: ../nova/objectstore/handler.py:235
#, python-format
msgid "Creating bucket %s"
msgstr ""

#: ../nova/objectstore/handler.py:245
#, python-format
msgid "Deleting bucket %s"
msgstr ""

#: ../nova/objectstore/handler.py:249
#, python-format
msgid "Unauthorized attempt to delete bucket %s"
msgstr ""

#: ../nova/objectstore/handler.py:273
#, python-format
msgid "Getting object: %(bname)s / %(nm)s"
msgstr ""

#: ../nova/objectstore/handler.py:276
#, python-format
msgid "Unauthorized attempt to get object %(nm)s from bucket %(bname)s"
msgstr ""

#: ../nova/objectstore/handler.py:296
#, python-format
msgid "Putting object: %(bname)s / %(nm)s"
msgstr ""

#: ../nova/objectstore/handler.py:299
#, python-format
msgid "Unauthorized attempt to upload object %(nm)s to bucket %(bname)s"
msgstr ""

#: ../nova/objectstore/handler.py:318
#, python-format
msgid "Deleting object: %(bname)s / %(nm)s"
msgstr ""

#: ../nova/objectstore/handler.py:322
#, python-format
msgid "Unauthorized attempt to delete object %(nm)s from bucket %(bname)s"
msgstr ""

#: ../nova/objectstore/handler.py:396
#, python-format
msgid "Not authorized to upload image: invalid directory %s"
msgstr ""

#: ../nova/objectstore/handler.py:404
#, python-format
msgid "Not authorized to upload image: unauthorized bucket %s"
msgstr ""

#: ../nova/objectstore/handler.py:409
#, python-format
msgid "Starting image upload: %s"
msgstr ""

#: ../nova/objectstore/handler.py:423
#, python-format
msgid "Not authorized to update attributes of image %s"
msgstr ""

#: ../nova/objectstore/handler.py:431
#, python-format
msgid "Toggling publicity flag of image %(image_id)s %(newstatus)r"
msgstr ""

#. other attributes imply update
#: ../nova/objectstore/handler.py:436
#, python-format
msgid "Updating user fields on image %s"
msgstr ""

#: ../nova/objectstore/handler.py:450
#, python-format
msgid "Unauthorized attempt to delete image %s"
msgstr ""

#: ../nova/objectstore/handler.py:455
#, python-format
msgid "Deleted image: %s"
msgstr ""

#: ../nova/auth/manager.py:277
#, python-format
msgid "Looking up user: %r"
msgstr ""

#: ../nova/auth/manager.py:281
#, python-format
msgid "Failed authorization for access key %s"
msgstr ""

#: ../nova/auth/manager.py:264
#, python-format
msgid "No user found for access key %s"
msgstr ""

#: ../nova/auth/manager.py:287
#, python-format
msgid "Using project name = user name (%s)"
msgstr ""

#: ../nova/auth/manager.py:294
#, python-format
msgid "failed authorization: no project named %(pjid)s (user=%(uname)s)"
msgstr ""

#: ../nova/auth/manager.py:279
#, python-format
msgid "No project called %s could be found"
msgstr ""

#: ../nova/auth/manager.py:303
#, python-format
msgid ""
"Failed authorization: user %(uname)s not admin and not member of project "
"%(pjname)s"
msgstr ""

#: ../nova/auth/manager.py:289
#, python-format
msgid "User %(uid)s is not a member of project %(pjid)s"
msgstr ""

#: ../nova/auth/manager.py:314 ../nova/auth/manager.py:336
#, python-format
msgid "Invalid signature for user %s"
msgstr ""

#: ../nova/auth/manager.py:299 ../nova/auth/manager.py:310
msgid "Signature does not match"
msgstr ""

#: ../nova/auth/manager.py:428
msgid "Must specify project"
msgstr ""

#: ../nova/auth/manager.py:414
#, python-format
msgid "The %s role can not be found"
msgstr ""

#: ../nova/auth/manager.py:416
#, python-format
msgid "The %s role is global only"
msgstr ""

#: ../nova/auth/manager.py:469
#, python-format
msgid "Adding role %(role)s to user %(uid)s in project %(pid)s"
msgstr ""

#: ../nova/auth/manager.py:472
#, python-format
msgid "Adding sitewide role %(role)s to user %(uid)s"
msgstr ""

#: ../nova/auth/manager.py:498
#, python-format
msgid "Removing role %(role)s from user %(uid)s on project %(pid)s"
msgstr ""

#: ../nova/auth/manager.py:501
#, python-format
msgid "Removing sitewide role %(role)s from user %(uid)s"
msgstr ""

#: ../nova/auth/manager.py:574
#, python-format
msgid "Created project %(name)s with manager %(manager_user)s"
msgstr ""

#: ../nova/auth/manager.py:592
#, python-format
msgid "modifying project %s"
msgstr ""

#: ../nova/auth/manager.py:604
#, python-format
msgid "Adding user %(uid)s to project %(pid)s"
msgstr ""

#: ../nova/auth/manager.py:625
#, python-format
msgid "Remove user %(uid)s from project %(pid)s"
msgstr ""

#: ../nova/auth/manager.py:655
#, python-format
msgid "Deleting project %s"
msgstr "删除项目 %s"

#: ../nova/auth/manager.py:713
#, python-format
msgid "Created user %(rvname)s (admin: %(rvadmin)r)"
msgstr ""

#: ../nova/auth/manager.py:722
#, python-format
msgid "Deleting user %s"
msgstr "删除用户 %s"

#: ../nova/auth/manager.py:732
#, python-format
msgid "Access Key change for user %s"
msgstr ""

#: ../nova/auth/manager.py:734
#, python-format
msgid "Secret Key change for user %s"
msgstr ""

#: ../nova/auth/manager.py:736
#, python-format
msgid "Admin status set to %(admin)r for user %(uid)s"
msgstr ""

#: ../nova/auth/manager.py:781
#, python-format
msgid "No vpn data for project %s"
msgstr "没有 %s 项目的vpn数据"

#: ../nova/service.py:141
#, python-format
msgid "Starting %(topic)s node (version %(vcs_string)s)"
msgstr ""

#: ../nova/service.py:232
msgid "Service killed that has no database entry"
msgstr "因无数据库记录，服务已被中止"

#: ../nova/service.py:266
msgid "The service database object disappeared, Recreating it."
msgstr ""

#: ../nova/service.py:278
msgid "Recovered model server connection!"
msgstr "与模型服务器(model server)的连接已恢复！"

#: ../nova/service.py:284
msgid "model server went away"
msgstr "失去与模型服务器的连接"

#: ../nova/auth/ldapdriver.py:174
#, python-format
msgid "LDAP user %s already exists"
msgstr "LDAP 用户 %s 已存在"

#: ../nova/auth/ldapdriver.py:205
#, python-format
msgid "LDAP object for %s doesn't exist"
msgstr ""

#: ../nova/auth/ldapdriver.py:348
#, python-format
msgid "User %s doesn't exist"
msgstr "用户 %s 不存在"

#: ../nova/auth/ldapdriver.py:472
#, python-format
msgid "Group can't be created because group %s already exists"
msgstr "组不能被创建，因为组 %s 已经存在"

#: ../nova/auth/ldapdriver.py:478
#, python-format
msgid "Group can't be created because user %s doesn't exist"
msgstr "组不能被创建，因为用户 %s 不存在"

#: ../nova/auth/ldapdriver.py:495
#, python-format
msgid "User %s can't be searched in group because the user doesn't exist"
msgstr ""

#: ../nova/auth/ldapdriver.py:507
#, python-format
msgid "User %s can't be added to the group because the user doesn't exist"
msgstr ""

#: ../nova/auth/ldapdriver.py:510 ../nova/auth/ldapdriver.py:521
#, python-format
msgid "The group at dn %s doesn't exist"
msgstr "识别名为 %s 的组不存在"

#: ../nova/exception.py:785
#, python-format
msgid "User %(uid)s is already a member of the group %(group_dn)s"
msgstr "用户 %(uid)s 已经是 组 %(group_dn)s 中的成员"

#: ../nova/auth/ldapdriver.py:524
#, python-format
msgid ""
"User %s can't be removed from the group because the user doesn't exist"
msgstr "用户 %s 不能从组中删除，因为这个用户不存在"

#: ../nova/auth/ldapdriver.py:528
#, python-format
msgid "User %s is not a member of the group"
msgstr "用户 %s 不是这个组的成员"

#: ../nova/auth/ldapdriver.py:621
#, python-format
msgid ""
"Attempted to remove the last member of a group. Deleting the group at %s "
"instead."
msgstr "尝试删除组中最后一个成员，用删除组 %s 来代替。"

#: ../nova/auth/ldapdriver.py:549
#, python-format
msgid "User %s can't be removed from all because the user doesn't exist"
msgstr "用户 %s 不能从系统中删除，因为这个用户不存在"

#: ../nova/auth/ldapdriver.py:564
#, python-format
msgid "Group at dn %s doesn't exist"
msgstr "可识别名为 %s 的组不存在"

#: ../nova/virt/xenapi/network_utils.py:55
#, python-format
msgid "Found non-unique network for bridge %s"
msgstr "发现网桥 %s 的网络不唯一"

#: ../nova/virt/xenapi/network_utils.py:58
#, python-format
msgid "Found no network for bridge %s"
msgstr "发现网桥 %s 没有网络"

#: ../nova/api/ec2/admin.py:145
#, python-format
msgid "Creating new user: %s"
msgstr "创建新用户: %s"

#: ../nova/api/ec2/admin.py:153
#, python-format
msgid "Deleting user: %s"
msgstr "删除用户: %s"

#: ../nova/api/ec2/admin.py:175
#, python-format
msgid "Adding role %(role)s to user %(user)s for project %(project)s"
msgstr "添加角色 %(role)s 给项目 %(project)s 中的用户 %(user)s"

#: ../nova/api/ec2/admin.py:179
#, python-format
msgid "Adding sitewide role %(role)s to user %(user)s"
msgstr "给用户 %(user)s 添加站点角色 %(role)s"

#: ../nova/api/ec2/admin.py:185
#, python-format
msgid "Removing role %(role)s from user %(user)s for project %(project)s"
msgstr "删除项目 %(project)s中用户 %(user)s的角色 %(role)s"

#: ../nova/api/ec2/admin.py:189
#, python-format
msgid "Removing sitewide role %(role)s from user %(user)s"
msgstr "删除用户 %(user)s 的站点角色 %(role)s"

#: ../nova/api/ec2/admin.py:194 ../nova/api/ec2/admin.py:271
msgid "operation must be add or remove"
msgstr "操作必须为添加或删除"

#: ../nova/api/ec2/admin.py:207
#, python-format
msgid "Getting x509 for user: %(name)s on project: %(project)s"
msgstr "获得用户: %(name)s 在项目 :%(project)s中的x509"

#: ../nova/api/ec2/admin.py:225
#, python-format
msgid "Create project %(name)s managed by %(manager_user)s"
msgstr "创建被%(manager_user)s 管理的项目 %(name)s"

#: ../nova/api/ec2/admin.py:238
#, python-format
msgid "Modify project: %(name)s managed by %(manager_user)s"
msgstr "更改被 %(manager_user)s 管理的项目: %(name)s"

#: ../nova/api/ec2/admin.py:248
#, python-format
msgid "Delete project: %s"
msgstr ""

#: ../nova/api/ec2/admin.py:262
#, python-format
msgid "Adding user %(user)s to project %(project)s"
msgstr "添加用户 %(user)s 到项目 %(project)s 中"

#: ../nova/api/ec2/admin.py:266
#, python-format
msgid "Removing user %(user)s from project %(project)s"
msgstr "从项目 %(project)s 中移除用户 %(user)s"

#~ msgid "Full set of FLAGS:"
#~ msgstr "FLAGS全集："

#~ msgid "No such process"
#~ msgstr "没有该进程"

#, python-format
#~ msgid "Serving %s"
#~ msgstr "正在为 %s 服务"

#, python-format
#~ msgid "pidfile %s does not exist. Daemon not running?\n"
#~ msgstr "pidfile %s　不存在，守护进程是否运行？\n"

#~ msgid "Wrong number of arguments."
#~ msgstr "错误参数个数。"
